### ISSUE TITLE
DOA using real data

### ISSUE THREAD

**Issue by Merlin7864** [LCAV/pyroomacoustics#101]
Hello, 

I am attempting to utilize the DOA algorithms for real world data sets from a mic array, and am curious as to what changes I would need to make or what I need to keep in mind when I am doing this.

**Comment by fakufaku** [comment]
Hi @Merlin7864 , there should not be much to change. You can use the (simulated) script [here](https://github.com/LCAV/pyroomacoustics/blob/master/examples/doa_algorithms.py) as an example. To use real data, you will need to replace the output from the simulation `aroom.mic_array.signals` by your recorded signals (read from a wav file I expect).

One problem that I have seen often is that with real recordings it is often unclear which channel corresponds to which physical microphone. If the order of the channels doesn't correspond to the microphone coordinates provided to the DOA object in the columns of the `R` matrix, in the script, the computed DOA will be wrong.

**Comment by Merlin7864** [comment]
Thank you, and I'm glad that the example code will perform well. As a follow on, do you happen to know the performance will be affected if the sound is transmitted through a medium with significantly higher sound speed and how it could be counteracted?

**Comment by fakufaku** [comment]
Hopefully the code will perform well... 😅 Keep in mind that you might have to tune the parameters of the algorithms depending on the signals and array aperture (choice of frequency bands, etc).
As for the follow up question, I don't think I have a good answer to that. It sounds challenging!

**Comment by Merlin7864** [comment]
Haha it is. Now trying to include spatial smoothing, any chance pyroomacoustics has that installed? lol

**Comment by fakufaku** [comment]
If by spatial smoothing you mean beamforming, you can take a look at the `beamforming` module.

**Comment by fakufaku** [comment]
Closed due to lack of activity.

**Comment by L0g4n** [comment]
> One problem that I have seen often is that with real recordings it is often unclear which channel corresponds to which physical microphone. If the order of the channels doesn't correspond to the microphone coordinates provided to the DOA object in the columns of the `R` matrix, in the script, the computed DOA will be wrong.
@fakufaku Reading this part of your reply, I wonder how I correctly associate my raw signals to my "virtual microphone array". I know which channel corresponds to which physical mic though.

**Comment by L0g4n** [comment]
@fakufaku So I found this sentence from the docs [HERE](https://pyroomacoustics.readthedocs.io/en/pypi-release/pyroomacoustics.room.html#simulate-sound-propagation).

> The output from the convolutions will be summed up at the microphones. The result is stored in the signals attribute of room.mic_array with each row corresponding to one microphone.

So, is it correct then to assume that the first row signals corresponds to the first row (first mic) in the R array and so on?

**Comment by fakufaku** [comment]
Yes, that is how it should be. The order of the channels in the STFT and the order of the microphones in `R` should match.

**Comment by L0g4n** [comment]
Edit: To be correct, the first row in my signal array corresponds to the first **column** in my R microphone array (not row).
