### ISSUE TITLE
Advice on measuring beamforming performance

### ISSUE THREAD

**Issue by taospartan** [LCAV/pyroomacoustics#103]
I’m simulating differing rooms and mic array shapes, I want to be able to generate a metric that shows the improvement or degradation of the beamformed signal. What we be the best way of achieving this?

Many thanks

Tao

**Comment by fakufaku** [comment]
You could look into the `bss_eval` toolkit. It is originally [matlab](http://bass-db.gforge.inria.fr/bss_eval/) but has been ported to Python in the [mir_eval](https://craffel.github.io/mir_eval/) package.

It was originally developed to evaluate source separation, but can be used for beamforming, etc. You can see it [in action](https://github.com/LCAV/pyroomacoustics/blob/master/examples/bss_example.py) in `examples/bss_example.py`. The metric is described in this paper:

> E. Vincent, R. Gribonval, and C. Fevotte, “Performance measurement in blind audio source separation,” IEEE Trans. Audio Speech Lang. Process., vol. 14, no. 4, pp. 1462–1469, Jun. 2006.

**Comment by taospartan** [comment]
That’s great, many thanks
