### ISSUE TITLE
Moving Sound Sources

### ISSUE THREAD

**Issue by arilato** [LCAV/pyroomacoustics#105]
Is it possible to use this package to simulate a moving sound source/moving microphone arrays?

Perhaps, setting a dense linear array of microphones and combining their shifted simulated recordings to simulate a change of the distance/angle between a single microphone and an audio source.

**Comment by fakufaku** [comment]
Sort of. You can add sources all along the trajectory and get the rir for
each of them. Then you need to do a time-varying convolution with the
source signal.

The two downsides are the computation time, and the lack of Doppler effect.
If the source speed is slow enough, the latter is probably not an issue.

**Comment by fakufaku** [comment]
Closed for lack of activity.
