### ISSUE TITLE
Frost Beamformer Performance

### ISSUE THREAD

**Issue by taospartan** [LCAV/pyroomacoustics#106]
Does anyone here have any experience with the frost beamformer? Does it perform as well as MVDR?

Many thanks

**Comment by fakufaku** [comment]
@taospartan I don't know Frost's beamformer (discovered it thanks to you), but I know the generalized sidelobe canceller (GSC) which is closely related and more recent (by ~10 years it seems). My understanding is that the GSC is an efficient adaptive implementation of MVDR.

I implemented GSC in a live demo and my experience is that it will work great if

1) Your constant beamformer is finely tuned to the target source. If not there will be some target cancellation.
2) In case of dynamic environment, the adaptive part should be fast enough to keep up. In my demo, I had to abandon LMS/NLMS in favor of the faster but more demanding RLS to get fast enough adaptation.

**Comment by wangwei2009** [comment]
@fakufaku is this live GSC demo included in pyroomacoustics package? I can't find it anywhere in this repo.
Thanks

**Comment by jazcarretao** [comment]
@taospartan you can find a C implementation of the demo here:
https://github.com/fakufaku/pyramic-demo

**Comment by taospartan** [comment]
Thank you for all the great information !

**Comment by taospartan** [comment]
@fakufaku I'm trying out the python sim code within https://github.com/fakufaku/pyramic-demo for the  gsc beam former but keep getting 
`/Library/Python/2.7/lib/python/site-packages/pyroomacoustics/transform/stft.py:336: UserWarning: Received 516746 samples. Appending 374 zeros for integer multiple of hops.
  extra_samples))
Segmentation fault: 11
` 
could you point me in the correct direction?

many thanks

Tao

**Comment by fakufaku** [comment]
Hi @taospartan , without telling us what exact code you are running, it is hard to help. Please provide clarification. If you identify a pyroomacoustics issue, please open a new issue here. If this is a GSC related issue, please post it in the pyramic-demo repository. Thanks!

**Comment by fakufaku** [comment]
@taospartan I was just made aware that issues were disabled on `pyramic-demo`! Sorry for that. I have just re-enabled them, so feel free to open one there.
