### ISSUE TITLE
[next_gen_simulator] std::exception when creating room with non convex walls

### ISSUE THREAD

**Issue by Chutlhu** [LCAV/pyroomacoustics#107]
Dear all,
I am trying to simulate RIR of a 3D non-convex room.
I was able to create the room and simulate the RIR from 3D mesh (.stl format).
(refer to this [issues](https://github.com/LCAV/pyroomacoustics/issues/98))
However, such mesh consisted in a collection of triangles.
For future use, I prefer to merge all the triangles in corresponding planes, the results of this computation can be found in this [shared folder](https://drive.google.com/open?id=1_stztUDrKZUMkEpqFZO1KnAEjtGy0rdY).

Unfortunately when using wall as non-convex polygon, `pra.wall_factory()` raises the following error:

```bash
Traceback (most recent call last):
  File "src/small_example_for_musis_with_non_cvx_wall.py", line 60, in <module>
    material.scattering["coeffs"],
  File "./pyroomacoustics/pyroomacoustics/room.py", line 315, in wall_factory
    name,
RuntimeError: std::exception
```

With the following code you can reproduce the issues:

```python
import glob
import numpy as np
import pyroomacoustics as pra
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
import matplotlib.colors as colors


def surface_normal_newell(poly):
    n = np.array([0.0, 0.0, 0.0])
    for i, v_curr in enumerate(poly):
        v_next = poly[(i+1) % len(poly), :]
        n[0] += (v_curr[1] - v_next[1]) * (v_curr[2] + v_next[2])
        n[1] += (v_curr[2] - v_next[2]) * (v_curr[0] + v_next[0])
        n[2] += (v_curr[0] - v_next[0]) * (v_curr[1] + v_next[1])
    norm = np.linalg.norm(n)
    if norm == 0:
        raise ValueError('zero norm')
    else:
        normalised = n/norm
    return normalised

def plot_poligons(plane_list):
    figure = plt.figure()
    axes = mplot3d.Axes3D(figure)
    for plane_coords in plane_list:
        b = np.mean(plane_coords, 1)
        n = surface_normal_newell(plane_coords.T)*1000
        poly = mplot3d.art3d.Poly3DCollection(
            [list(zip(plane_coords[0, :], plane_coords[1, :], plane_coords[2, :]))],
            alpha=0.2)
        poly.set_color(colors.rgb2hex(np.random.random(3)))
        axes.quiver(b[0], b[1], b[2], n[0], n[1], n[2], color='red')
        axes.add_collection3d(poly, zs='z')
    return axes

# list the wall files
plane_files = glob.glob('./path/to/wall*.csv')
planes = []
for pfile in plane_files:
    plane_coords = np.loadtxt(pfile, delimiter=',')
    planes.append(plane_coords)

# plot planes
plot_poligons(planes)
plt.show()

# generate corresponding pra's walls
material = pra.Material.make_freq_flat(0.2)
walls = []
for p, plane in enumerate(planes):
    walls.append(
        pra.wall_factory(
            plane,
            material.absorption["coeffs"],
            material.scattering["coeffs"],
        )
    )
```

What am I doing wrong? Is it because of the non-convexity of the wall polygon?
Thank you very much

**Comment by fakufaku** [comment]
Sorry for the cryptic error message. There should be a clearer error message which was not displayed. I have now added the proper error message.

The error is that some of the point sets defining the walls are not perfectly planar. When you create the wall, an SVD is run on the matrix formed by all the corners of the wall translated to the origin by subtracting any of the points:
```
[ [ x_2 - x_1, ..., x_n - x_1 ],
  [ y_2 - y_1, ..., y_n - y_1 ],
  [ z_2 - z_1, ..., z_n - z_1 ] ]
```
When the points all lie in the same plane, the smallest singular value should be very close to zero. In the library, I check for `eps ~ 1e-6`. In your case, `planes[3]` and `planes[4]` do not satisfy this, the smallest singular values are `0.3` and `1e-4`, respectively.

**Comment by Chutlhu** [comment]
Thank you very much,
Yes you are right, the vertices of the wall seems to be no-coplanar.
I will check why SketchUp is not returning walls with coplanar vertices.

**Comment by fakufaku** [comment]
Closing this as it seems resolved.
