### ISSUE TITLE
how to implement Griffin Lim using pyroomacoustics

### ISSUE THREAD

**Issue by tsungruihon** [LCAV/pyroomacoustics#109]
how to implement Griffin Lim using pyroomacoustics ?

**Comment by tsungruihon** [comment]
I have noticed that `Griffin Lim` in `phrase` directory. And it seems that it could not synthesis in real-time?

**Comment by fakufaku** [comment]
As you found out, there is a newly added implementation of the Griffin-Lim phase reconstruction algorithm in the master branch. You can find its documentation in the `latest` version of the [documentation](https://pyroomacoustics.readthedocs.io/en/latest/pyroomacoustics.phase.gl.html#module-pyroomacoustics.phase.gl). Note that this is not yet on pypi, but I will release soon a new version including it.

This GL implementation is indeed not meant for real-time processing.

**Comment by tsungruihon** [comment]
@fakufaku thanks my friend. I also noticed that even if i changed `transform` to `pyfftw` or `mkl` with `threads=4`, it could not processing in real-time.

**Comment by fakufaku** [comment]
You should note that the processing time needed will depend on the number of iterations you run.

**Comment by tsungruihon** [comment]
@fakufaku Yes indeed.  By the way, may i ask whether you have used `[LTFAT](https://github.com/ltfat/ltfat)`

**Comment by fakufaku** [comment]
I know about this library, but I have never used it myself. It looks very nice.

**Comment by tsungruihon** [comment]
@fakufaku thanks my friend.  Now i stuck at building `ltfat` with `make`. https://github.com/ltfat/ltfat/tree/master/libltfat. If you succeed, please let me know lol.
