### ISSUE TITLE
rake_perceptual_filter no interferer

### ISSUE THREAD

**Issue by taospartan** [LCAV/pyroomacoustics#110]
I'm trying to use the rake_perceptual_filter with no interferer, the documentation states

`rake_perceptual_filters(source, interferer=None, R_n=None, delay=0.03, d_relax=0.035, epsilon=0.005)`

when I try to run the command I get the following error:

 `mics.rake_perceptual_filters(room1.sources[0][0:1], interferer=None, sigma2_n*np.eye(mics.Lg*mics.M), delay)`
SyntaxError: non-keyword arg after keyword arg

Any help would be appreciated, 

many thanks

tao

**Comment by fakufaku** [comment]
Hi @taospartan , this seems to be a Python syntax error. Python functions have two types of arguments: *non-keyword* and *keyword* arguments. Keyword arguments have a default value, e.g. `delay=0.03`. So in
```
rake_perceptual_filters(source, interferer=None, R_n=None, delay=0.03, d_relax=0.035, epsilon=0.005)
```
`source` is a *non-keyword argument* and `interferer`, `R_n`, etc, are *keyword arguments*. One rue is that keyword arguments need to be specified **after** non-keyword arguments. In your case, I think you forgot to add the keyword in front of the argument for `R_n` and `delay`. The correct call would be
```
mics.rake_perceptual_filters(room1.sources[0][0:1], interferer=None, R_n=sigma2_n*np.eye(mics.Lg*mics.M), delay=delay)
```

**Comment by taospartan** [comment]
Thanks for the reply but with this command

`mics.rake_perceptual_filters(room1.sources[0], interferer=None, R_n=None, delay=0.03, d_relax=0.035, epsilon=0.005)`

I get the error

```
File "/Users/test/Library/Python/2.7/lib/python/site-packages/scipy/linalg/decomp_cholesky.py", line 40, in _cholesky
    "definite" % info)
numpy.linalg.LinAlgError: 1-th leading minor of the array is not positive definite
```

**Comment by fakufaku** [comment]
I see. For this beamformer, `R_n` needs to be a full rank matrix. I apologize for the interface to this function that is poorly documented. Internally, a linear system is solved and in case the matrix formed by the combination of `interferer` and `R_n` is rank deficient, an error occur. I will put this on my todo list. For the time being, you can provide `R_n=sigma2_n * np.eye(mics.Lg * mics.M)` for example.

**Comment by taospartan** [comment]
Many thanks:)

**Comment by taospartan** [comment]
Replacing the R_n=sigma2_n * np.eye(mics.Lg * mics.M) now results in this error 

`    mics.rake_perceptual_filters(room1.sources[0], interferer=None, R_n=sigma2_n * np.eye(mics.Lg * mics.M), delay=0.03, d_relax=0.035, epsilon=0.005)
  File "/Users/test/Library/Python/2.7/lib/python/site-packages/pyroomacoustics/beamforming.py", line 1119, in rake_perceptual_filters
    C = la.cho_factor(D, overwrite_a=True, check_finite=False)
  File "/Users/test/Library/Python/2.7/lib/python/site-packages/scipy/linalg/decomp_cholesky.py", line 155, in cho_factor
    check_finite=check_finite)
  File "/Users/test/Library/Python/2.7/lib/python/site-packages/scipy/linalg/decomp_cholesky.py", line 40, in _cholesky
    "definite" % info)
numpy.linalg.LinAlgError: 6177-th leading minor of the array is not positive definite`

any ideas?

many thanks

tao

**Comment by taospartan** [comment]
ignore me I made a syntax error.

sorry

tao

**Comment by fakufaku** [comment]
Great, happy this is working now!
