### ISSUE TITLE
Obstacles in the Room

### ISSUE THREAD

**Issue by luisgonzalex** [LCAV/pyroomacoustics#112]
We are interested in using pyroomacoustics to simulate different combinations of microphone arrays, rooms, and locations of source(s) to create a database of recordings from simulations for our research. For our purposes, we are trying to model several rooms that have multiple obstacles, for example, pillars, desks, closets, and doors. We were wondering if your package already supports building these kinds of rooms, and if so, how could it be done? If not, since the group is in the field of acoustics, what kind of software do you know is able to do this? Thanks in advance.

**Comment by fakufaku** [comment]
Hi @luisgonzalex , thanks for your interest. The package actually support non-convex rooms, but is currently very very slow for these. We are working on a more advanced simulator that will support these more naturally and in a more reasonnable time in the branch `next_gen_simulator`. Unfortunately, this is not really ready for production and we haven't tested that everything works. While the new simulator is orders of magnitude faster than the current one, it might still not be able to support model with too many polygons.
There are a few alternatives that I know of, but haven't used
* [odeon](https://odeon.dk/) (paid)
* [i-simpa](http://i-simpa.ifsttar.fr/) (free, gui around some other too it seems)
* [catt](https://www.catt.se/)  (paid?, windows only)
* [wayverb](https://github.com/reuk/wayverb) (open source, gui, mac only)

**Comment by fakufaku** [comment]
Closed for lack of activity.
