### ISSUE TITLE
3D Grid implementation

### ISSUE THREAD

**Issue by deepchand41** [LCAV/pyroomacoustics#114]
Hi @fakufaku I am trying to implement 3D sound source localization i.e. estimation of Azimuth as well as Elevation angle by using Grid Search. I found that your library contains Grid Object. So would you please explain how to implement that object for circular microphone array.

**Comment by fakufaku** [comment]
@deepchand41 Sorry for the very late answer. Essentially, the grid object is independent of the shape of the microphone array. It only samples points pseudo-uniformly on the sphere, i.e. unit vectors pointing in all directions. You can check out the [source code](https://github.com/LCAV/pyroomacoustics/blob/master/pyroomacoustics/doa/grid.py#L146) directly to see how this is implemented. The method is called Fibonacci mapping and is fairly easy to implement. It is described in the second answer to this [question](https://stackoverflow.com/questions/9600801/evenly-distributing-n-points-on-a-sphere) on stackoverflow.

For grid search method, you want to evaluate your objective function for a number of steering vectors corresponding to different directions on the sphere. Steering vectors can be computed from the unit vector `p` corresponding to one position on the grid and the location `r_n` of the `n`-th microphone. `p` and `r_n` both are 3D vectors. Then the `n`-th coordinate of the steering vector is `exp(-j (omega / c) * inner(p, r_n))` or similar (`omega` is the angular frequency, `c` the speed of sound and `j = sqrt(-1)`). In case your algorithm uses time difference of arrival, you might need to adjust the microphone location to `r'_n = r_n - r_0` where `r_0` is the reference microphone. In this case, `inner(p, r_n - r_0) / c` is just the expected time delay between microphone `0` and `n`.

**Comment by fakufaku** [comment]
Closed due to lack of activity.
