### ISSUE TITLE
Support of closed/rigid microphone arrays

### ISSUE THREAD

**Issue by nilspo** [LCAV/pyroomacoustics#118]
First of all thank you for this great toolbox. I am very excited about this package and it is exactly what I was looking for.
Nevertheless, I have a question or suggestion. Is it possible or planned to support closed/rigid microphone arrays?

**Comment by fakufaku** [comment]
@nilspo Thank you! We are definitely thinking of adding directive response to the microphones, which I think would fit the bill. However, we are currently busy with adding a few other features (better diffuse response simulation, random room generators, etc) and the microphone directivity is not really on the horizon yet... So planned, yes, but I can't tell you when this will be available.

If you want to add some custom code to do it, I have briefly explained in issue #95 how that could be done with the current simulator.
