### ISSUE TITLE
How is the mark of the microphone array signal generated?

### ISSUE THREAD

**Issue by xiaojian10** [LCAV/pyroomacoustics#119]
![image](https://user-images.githubusercontent.com/43231974/62418731-3a90bf80-b6a3-11e9-930d-d6ed97204541.png)
 The above line marks -1 as the center signal, and the microphone array has 6 sources. I found that there are 7 lines in room_bf.mic_array.signals[-1,:]. I can change the -1 to 7 to output the signal. I don't know why? Can you answer me in your free time?

**Comment by fakufaku** [comment]
Hi @xiaojian10 . Sure, this seems to by a Python/numpy related question. In numpy (and Python lists), negative indices are counted from the back of the array. See this [link](https://docs.scipy.org/doc/numpy-1.17.0/reference/arrays.indexing.html) for more information about indexing in numpy. Here is an example with a Python list.
```
my_list = [1, 2, 3, 4]
print(my_list[-1])  # prints 4
print(my_list[3])  # also prints 4
print(my_list[-2])  # prints 3
```
In the code pasted above, the array is created by forming first a circular array
```
# echo is a 2x6 numpy array
echo = pra.circular_2D_array(center=center, M=6, phi0=0, radius=radius)
```
and then concatenating the center location to form a 7-microphone array
```
# echo is now a 2x7 numpy array
echo = np.concatenate((echo, np.array(center, ndmin=2).T), axis=1)
```
I hope this clarifies things somewhat.

**Comment by xiaojian10** [comment]
Thank you for your time and clarified explanation  . I will really appreciate it if I can turn to you for futther questions about your shared code.

**Comment by xiaojian10** [comment]
I think the code you shared is very convenient for beamforming, it was a great module.  And now, I would like to do subarray beamforming, but I didn't find anything about this in the code you shared. Can your code do subarray beamforming? If the code is ok, can you give me some examples in your  free time?
