### ISSUE TITLE
Differences with other libraries

### ISSUE THREAD

**Issue by DavidDiazGuerra** [LCAV/pyroomacoustics#126]
Hello,

I've been comparing the RIRs simulated with pyroomacoustics with the simulated by other libraries and I've found a couple of differences that I don't know where they come from. Compared with [pyrirgen](https://github.com/Marvin182/rir-generator/tree/master/python) the reverberation simulated with pyroomacoustics is quite shorter and is delayed about 39~40 samples:

```python
import numpy as np
import matplotlib.pyplot as plt

import pyroomacoustics as pra
import pyrirgen

room_sz = [3, 4, 2.5]
fs = 16000.0
c = 343.0

pos_src = np.array([1, 2.5, 1])
pos_rcv = np.array([2, 1.5, 2])

def sabine_T60(room_sz, alpha):
	Sa = (alpha[0] + alpha[1]) * room_sz[1] * room_sz[2] + \
		 (alpha[2] + alpha[3]) * room_sz[0] * room_sz[2] + \
		 (alpha[4] + alpha[5]) * room_sz[0] * room_sz[1]
	V = np.prod(room_sz)
	return 0 if Sa == 0 else 0.161 * V / Sa

beta = 0.85 * np.ones((6))
alpha = 1 - beta**2
T60 = sabine_T60(room_sz, alpha)
nb_img = int( np.fix( T60 * c / min(room_sz) ) )

room = pra.ShoeBox(room_sz, fs=fs, absorption=(alpha).item(0), max_order=nb_img) 
room.add_source(pos_src)
mic_array = pra.MicrophoneArray( np.array(pos_rcv).reshape((3,1)), room.fs ) 
room.add_microphone_array( mic_array )

room.compute_rir()
RIR_pra = room.rir[0][0]

RIR_prg = pyrirgen.generateRir(room_sz, pos_src, pos_rcv, fs=fs, betaCoeffs=beta, nSamples=RIR_pra.shape[0], isHighPassFilter=False)

t = np.arange(RIR_pra.shape[0]) / fs
plt.plot(t, RIR_prg)
plt.plot(t, RIR_pra)
plt.show()
```

![pra_vs_prg](https://user-images.githubusercontent.com/43950921/64947200-c84ff500-d874-11e9-9c3a-cff4f3f4e6af.png)

I also simulated the same setup with [gpuRIR](https://github.com/DavidDiazGuerra/gpuRIR) and with [this Matab library](http://www.eric-lehmann.com/ism_code.html) and, though the results are quite different because of the use of negative reflection coefficients, both the reverberation length and the initial dealy are similar to the the results of `pyrirgen`.

Do you know what is the reason for these differences? Am I misusing your library in any way?

Thanks, 
David

**Comment by DavidDiazGuerra** [comment]
Hello again,

I think I found why I got shorter RIRs with pyroomacoustics than with other libraries. In your [documentation](https://pyroomacoustics.readthedocs.io/en/pypi-release/pyroomacoustics.room.html#create-the-room), you indicate that:

> reflections are multiplied by `(1 - absorption)` for every wall they hit

and this is also indicated the equation (1) of [your paper](https://arxiv.org/pdf/1710.04196.pdf).

However, the absorption coefficient (`alpha`) is typically defined in terms of acoustic intensity, so the reflections should be multiplied by `(1 - alpha**2)` each time they hit a wall. This is indicated in the equation (9) of [the original paper of the ISM by Allen and Berkley](https://pdfs.semanticscholar.org/1182/8b545524ae714aa7e527d42ed08e4d126655.pdf).

If I use `alpha = 1 - beta` instead of `alpha = 1 - beta**2` in my previous example, the T60 computed with the Sabine formula is wrong, but the RIR is more similar to the computed with 'pyrirgen':

![pra_vs_prg_v2](https://user-images.githubusercontent.com/43950921/64950477-bcb3fc80-d87b-11e9-85e9-3d46776a4066.png)

The dealy is still present between both RIRs.

**Comment by fakufaku** [comment]
Hi @DavidDiazGuerra , you are right! I made this terminology error early on and have been planning to correct it in some upcoming version. I am planning to add a new keyword `energy_absorption` that should take the acoustically accepted definition of absortion. Then, I'll phase out the ambiguous `absorption` keyword. Do you think that would help avoid misunderstanding ?

The delay of 40 samples is due to the use of a fractional delay filter of 81 samples length. This means the origin of time is always the 41st sample.

**Comment by DavidDiazGuerra** [comment]
Hi @fakufaku, I agree that the `energy_absorption` keyword would be a good solution. Actually, I think it would be great if everybody specifies energy/amplitude when speaking about reflection or absorption coefficients... it is quite ambiguous and it leads to confusion even in many papers (I think I found a mistake in Wikipedia related to it).

If the delay is the same for every RIR it should not be a problem.

Thanks for the quick response, you have an amazing library!

**Comment by fakufaku** [comment]
Thanks for the feedback and kind words! Out of curiosity, after correcting the "absorption" and accounting for the 40 samples, how much do the RIRs differ ?

**Comment by DavidDiazGuerra** [comment]
These are the RIRs generated with `pyroomacoustics` and with `pyrirgen` at different time instants and the difference between them after correcting the absorption coefficient and the initial delay:

![pra_vs_prg_v3_1](https://user-images.githubusercontent.com/43950921/65223756-2887a680-dac2-11e9-86c0-d84bb5192274.png)

![pra_vs_prg_v3_2](https://user-images.githubusercontent.com/43950921/65224124-db580480-dac2-11e9-8cd5-3d4c345ce5d0.png)

![pra_vs_prg_v3_3](https://user-images.githubusercontent.com/43950921/65223781-32a9a500-dac2-11e9-9eda-c02e047fdc43.png)

![pra_vs_prg_v3_4](https://user-images.githubusercontent.com/43950921/65223786-35a49580-dac2-11e9-9dc7-1eabb3a3069c.png)

![pra_vs_prg_v3_5](https://user-images.githubusercontent.com/43950921/65223792-3806ef80-dac2-11e9-9336-9a602dc51333.png)

In the third image it seems that there is some delay between both RIRs, but this is not so clear in the fourth.

**Comment by fakufaku** [comment]
Thank you very much, very interesting. It looks that there is some kind of time delay. Is the speed of sound set to the exact same value ?
After a while (i.e. 0.1 s), I would guess that the mixing is such that a time delay cannot be detected visually anymore.

**Comment by DavidDiazGuerra** [comment]
You were right, `pyroomacoustics` uses `c=343` by deffault while `pyrirgen` uses `c=340`. After modifing the speed of sound in `pyrirgen` now both RIRs are basically the same:

![pra_vs_prg_v4_5](https://user-images.githubusercontent.com/43950921/65231896-8622ef80-dad0-11e9-8d7b-1bfbb1c9e749.png)
