### ISSUE TITLE
Reverberation time

### ISSUE THREAD

**Issue by xiaojian10** [LCAV/pyroomacoustics#129]
This is a great project, I try to do some research on the voice with the code you share. But I am currently a newbie. In your code, the definition of the room includes the absorption and max_order parameters. And your explanation is as follows,
![image](https://user-images.githubusercontent.com/43231974/65825158-34375200-e2a6-11e9-9f23-d37a52708d32.png)
I don't quite understand what you mean. and I know how the relationship between absorption and max_order and reverberation time is? If I want to set the room's reverb time to 0.3 seconds, how do I set the values of these two parameters in the code? I hope you can explain it when you have time. I will be very grateful.

**Comment by fakufaku** [comment]
oorry for the long reply time. I have been planning for some time to add code to set automatically the `absorption` and `max_order`, but haven't got around doing that yet.

However, I can share here with you the function I am using privately. Just be aware that this function only works approximately, especially in the case of the image source model. This means that when you actually measure the RT60 from the created room, you might get a value that is not exactly the desired one. Also, you need to make sure that sound source and microphones are separated at least by the [critical distance](https://en.wikipedia.org/wiki/Critical_distance).

Here you go.
```
def inv_sabine(t60, room_dim, c):
    """
    given desired t60, (shoebox) room dimension and sound speed,
    computes the absorption coefficient (amplitude) and image source
    order needed.

    parameters
    ----------
    t60: float
        desired t60 (time it takes to go from full amplitude to 60 db decay) in seconds
    room_dim: list of floats
        list of length 2 or 3 of the room side lengths
    c: float
        speed of sound

    returns
    -------
    absorption: float
        the absorption coefficient (in amplitude domain, to be passed to
        room constructor)
    max_order: int
        the maximum image source order necessary to achieve the desired t60
    """

    # finding image sources up to a maximum order creates a (possibly 3d) diamond
    # like pile of (reflected) rooms. now we need to find the image source model order
    # so that reflections at a distance of at least up to ``c * rt60`` are included.
    # one possibility is to find the largest sphere (or circle in 2d) that fits in the
    # diamond. this is what we are doing here.
    R = []
    for l1, l2 in itertools.combinations(room_dim, 2):
        R.append(l1 * l2 / np.sqrt(l1 ** 2 + l2 ** 2))

    V = np.prod(room_dim)  # area (2d) or volume (3d)
    # "surface" computation is diff for 2d and 3d
    if len(room_dim) == 2:
        S = 2 * np.sum(room_dim)
        sab_coef = 12  # the sabine's coefficient needs to be adjusted in 2d
    elif len(room_dim) == 3:
        S = 2 * np.sum([l1 * l2 for l1, l2 in itertools.combinations(room_dim, 2)])
        sab_coef = 24

    a2 = sab_coef * np.log(10) * V / (c * S * t60)  # absorption in power (sabine)

    if a2 > 1.0:
        raise ValueError(
            "evaluation of parameters failed. room may be too large for required t60."
        )

    absorption = 1 - np.sqrt(1 - a2)  # convert to reflection coefficient

    max_order = math.ceil(c * t60 / np.min(R) - 1)

    return absorption, max_order
```
