### ISSUE TITLE
Minor Issue in Demo Notebook for DOA

### ISSUE THREAD

**Issue by ShawnHymel** [LCAV/pyroomacoustics#144]
In the [Demo Notebook](https://nbviewer.jupyter.org/github/LCAV/pyroomacoustics/blob/master/notebooks/pyroomacoustics_demo.ipynb), I noticed that the center microphone is off. Here is the original code:

```
echo = pra.circular_2D_array(center=room_dim/2, M=6, phi0=0, radius=37.5e-3)
echo = np.concatenate((echo, np.array(center, ndmin=2).T), axis=1)
aroom.add_microphone_array(pra.MicrophoneArray(echo, aroom.fs))
```

I believe that the center speaker `center` coordinates were previously defined in the Beamforming example and don't apply to the DOA example. As a result, I recommend changing the array's center mic to the following:

```
echo = pra.circular_2D_array(center=room_dim/2, M=6, phi0=0, radius=37.5e-3)
echo = np.concatenate((echo, np.array(room_dim/2, ndmin=2).T), axis=1)
aroom.add_microphone_array(pra.MicrophoneArray(echo, aroom.fs))
```

This seems to produce much better results in the spatial spectra diagrams: 

![image](https://user-images.githubusercontent.com/5232145/73317705-9bd1bf80-41fc-11ea-8dc3-43f65dae42c2.png)

I would PR this fix, but my Notebook is puking warnings everywhere that I'm sure you don't want seen on the demo page :)

**Comment by fakufaku** [comment]
Hi @ShawnHymel , nice catch, thanks! I'll be fixing that shortly!
