### ISSUE TITLE
Polar pattern for multiple receivers in next_gen implementation

### ISSUE THREAD

**Issue by xefonon** [LCAV/pyroomacoustics#154]
Hi, 
I am using the next_gen_simulator branch since I would like to apply the absorption and scattering coefficients (stochastic ray-tracing) on each wall object option that you have available. Thanks for that!
I am also trying to apply a polar pattern for the mics since I would like to use first order ambisonics (B-Format IRs). I realise you have a solution for applying directional attenuation for each image source etc in other issues raised in the past but I was wondering if you have implemented it yet so I don't start 'hacking' your wonderful code! 

Thanks.

**Comment by fakufaku** [comment]
Hi @xefonon and sorry for the late reply. Sadly I did not have time to start implementing any of this. In case you start something and want to share it that would be immensely appreciated.

**Comment by xefonon** [comment]
@xefonon Thanks for the reply! Sure, I will attempt to!
