### ISSUE TITLE
How to add several sound sources, in a room with only one sound signal available 

### ISSUE THREAD

**Issue by torbjoif** [LCAV/pyroomacoustics#158]
I want to record sound in a room with multiple sound sources, but without attaching a specific signal from each source.
Imagine if I were to place a microphone array into a room where I only know the locations of the sources, but not what sounds that individually emit.
I only record all of the sounds combined.

From this, I want to generate a RIR.
I want the final result to be a sound with no echo and no reverberant sounds before passing it on to the next algorithm.

 Any advice?

Right now I am adding one source with one signal, then room.simulate() to get a better sound in return.
` 

room = pra.ShoeBox(room_dim, =fs, absorption=absorption, max_order=max_order)

    # add source and set the signal to WAV file content. NB: SoundSource must ne np.array()
      room.add_source(soundSource3DLoc,
                    signal=soundData_i)  # changed to Global var soundSource3DLoc

    # add one-microphone 3D XYZ array add coordinates of every mic
    room.add_microphone_array(pra.MicrophoneArray(room_mic_XYZ_locations,
                                                  room.fs))
    room.image_source_model(use_libroom=False)
    """gets the impulse response between mic and source"""
    ir = room.compute_rir()
    """calculates the n samples before sound dissipates with 60 db"""
    t60_samples = pra.experimental.measure_rt60(ir)
    """calculates the time in sec before sound dissipates with 60 db"""
    t60_s = pra.experimental.measure_rt60(ir, fs=fs)
    """Then the target RT60 and the estimated RT60 match really well! Now I haven't made this change just yet because 
    there are some caveats. First, I believe a in Sabine's formula relates to energy, while the reflection coefficient
     is in amplitude (hence the original computation for the reflection). This might mean that there is a problem with
      for example the estimation of the RT60 itself."""
    # absorption, max_order = inv_sabine(t60=t60_s, room_dim=room_dim, c=speedOfSound) #

    # visualize 3D polyhedron room and image sources
    if visualizeRoom:
        fig, ax = room.plot(img_order=max_order)
        fig.set_size_inches(5, 2, forward=False)
        plt.show()
    """Moreover, we can plot the RIR for each microphone once the image sources have been computed."""
    if visualizeRoom:
        plt.figure()
        room.plot_rir()
        fig = plt.gcf()
        fig.set_size_inches(5, 2, forward=False)
        plt.show()

    """Moreover, we can simulate our signal convolved with these impulse responses as such:"""
    room.simulate(reference_mic=0)  # this method must be called to get access to filteredSound
    """returns the filtered sound"""
    return room.mic_array.signals[0, 0:nFrames]  #`

**Comment by fakufaku** [comment]
I am not completely sure I understand the question. Are you asking a technical question about the use of the library, or is it a general question about audio signal processing and enhancement ?

**Comment by torbjoif** [comment]
Sorry for being unprecise.

I’m recording a sound in a room with several motors.
And I want to remove echo and reverbrant sound with the ISM simulator. Like in the notebook example where the sound was much clearer after the simulation.

But what if I only have one single recording of all the combined sources in a room. So when I’m supposed to attach a signal to every source at every location, I don’t have a separate signal for every source.
Imagine placing a microphone array in a machine room, entering where all sources are and the mic array’s locations.

What would you do in this library. Any suggestions?

Kind regards,
Tor

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fakufaku** [comment]
I think there is a misunderstanding. The ISM simulator does not remove echo or noise. Quite the opposite, it adds reverberation to a dry signal to simulate what happens in a real recording.

If you want to do some enhancement on recordings you have, you should look at the other modules in the package: `denoise`, `bss`, or `beamforming`. What example in the notebook are you referring to ?

**Comment by torbjoif** [comment]
Okey! I thought the RIR is the signature of the room, and one can inverse convulate this RIR with the original signal to remove echo and reverbrant sound.

I meant this example:
https://github.com/LCAV/pyroomacoustics/blob/master/notebooks/pyroomacoustics_demo.ipynb


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by torbjoif** [comment]
> I think there is a misunderstanding. The ISM simulator does not remove echo or noise. Quite the opposite, it adds reverberation to a dry signal to simulate what happens in a real recording.
> 
> If you want to do some enhancement on recordings you have, you should look at the other modules in the package: `denoise`, `bss`, or `beamforming`. What example in the notebook are you referring to ?

Do you think it is possible to inverse involve (deconvolve) the RIR which I got from a wet sound which already has reverb in it?
I tried to denoise, but unfortunately I did not get any result which can be played

**Comment by fakufaku** [comment]
If you don't know the reverb exactly, this is actually a fairly hard problem. You could try some blind dereverberation to reduce the length of the reverb. An implementation of a popular algorithm (WPE) is available here: https://github.com/fgnt/nara_wpe

If you have a multichannel recording (done with synced microphones), you can try using the `bss` package. This will not reduce the reverb but will separate different sources, assuming they do not move. If the sources are moving, this gets really hard.
