### ISSUE TITLE
Inaccuracies in actual vs theoretical tdoa (offset)

### ISSUE THREAD

**Issue by JonathanDZiegler** [LCAV/pyroomacoustics#161]
First of all, thank you very much for sharing your work!

While setting up various beamformers, it has become apparent to me that for some reason the geometric time delays and the delays created in the simulation differ by a constant value, in my case 40 samples.
Varying room dimensions, processing orders, the speed of sound (via `pra.constants.set('c')` ), the sampling rate...nothing seems to affect the offset. What am I missing?

This code shows the behavior described above:

```python
import pyroomacoustics as pra
import numpy as np
import matplotlib.pyplot as plt


def interpolated_shift(sequence, shift_samples):
    """
    Shifts time series sequence using linear interpolation
    :param sequence: time sequence to be shifted, np.array with time on first axis.
    :param shift_samples: float value of shift to be performed
    :return: input time series with shifted axis 0
    """
    sequence_data_positions = np.arange(len(sequence))
    shifted_positions = sequence_data_positions + shift_samples
    x0 = shifted_positions.astype(np.int32)
    x1 = (x0 + 1)
    m = shifted_positions - x0
    x0 = np.clip(0, len(sequence) - 1, x0)
    x1 = np.clip(0, len(sequence) - 1, x1)
    shifted_sequence = (1.0 - m) * sequence[x0] + m * sequence[x1]
    return shifted_sequence


if __name__ == "__main__":
    sampling_rate = 48000
    signal = np.random.normal(0, 0.1, (5000,))
    signal[0:10] = 1
    room = pra.ShoeBox([5, 8, 5], fs=sampling_rate, absorption=0.9, max_order=17)
    signal_position = [3, 6, 3]
    receiver_position = np.array([[2, 4, 3]]).T
    receiver = pra.MicrophoneArray(receiver_position, fs=sampling_rate)
    room.add_source(signal_position, signal=signal)
    room.add_microphone_array(receiver)
    room.simulate()
    result = room.mic_array.signals[0]
    result /= np.max(np.abs(result))  # normalization for plots

    # compensate shift, using geometric information from room class
    sig_pos = room.sources[0].position
    mic_pos = room.mic_array.R
    sig_to_mic_distance = np.linalg.norm(mic_pos - sig_pos[:, None], axis=0)
    sig_to_mic_time = sig_to_mic_distance / pra.constants.get('c')
    sig_to_mic_samples = sig_to_mic_time * sampling_rate
    compensated_sig = interpolated_shift(result, sig_to_mic_samples[0])
    ir_peak = np.argmax(room.rir[0][0])
    print("Difference between computed delay and RIR initial peak: {}".format(sig_to_mic_samples - ir_peak))

    # plot results
    plot_len = 500
    plt.plot(signal[:plot_len], label='input')
    plt.plot(result[:plot_len], alpha=0.5, label='simulated')
    plt.plot(compensated_sig[:plot_len], alpha=0.5, label='compensated')
    plt.grid(True)
    plt.legend()
    plt.show()

    plt.show()


```

**Comment by fakufaku** [comment]
I'm sorry this caused you trouble! The 40 samples offset that you discovered is in fact expected and is the result of using fractional delays to build the room impulse response. The fractional delays are 91 samples long (with peak at the middle), and to account for sources that might be closer to the microphone than 40 samples flight time, the RIR are padded with 40 samples at the beginning.

If you have an idea on how to make this more explicit in the doc or the code, please let me know!

**Comment by JonathanDZiegler** [comment]
@fakufaku thank you so much for your swift reply, that absolutely covers my question! I have incorporated a lower bound for source to microphone distance anyway, as it seems like the levels diverge at some point. Perhaps just add a short comment in the documentation of the room.simulate() and room.compute_rir() modules? The only place that hints at this (to my perception) is 
``` python
# fractional delay length
fdl = constants.get('frac_delay_length')
```
in the `get_rir` module. 

Thanks again for clearing this up!

**Comment by fakufaku** [comment]
Great! Some work on the documentation is overdue anyway, so I'll add this at the same time. Thanks for the feedback.

Indeed, a source can't reasonably be too close to the microphone or the level difference goes to infinity. However, the 40 samples is something like 85 cm at 16 kHz, which is a little bit too large for a hard limit, which is why I chose to pad the RIR instead.
