### ISSUE TITLE
Question about Beamformer

### ISSUE THREAD

**Issue by nanaChang** [LCAV/pyroomacoustics#171]
Hi, 

First of all thank you for implementing this library! It's awesome and I really had a lot of fun playing with it! :)

In my model, I'm trying to beamform a 4-channel array received by a mic array. The only known information about the data is the DoA (which is computed by DoA algorithm from the package), with the actual location unknown. Therefore, I chose `far_field_weights()` as my beamformer. 
However, I'm wondering if I want to use other Beamformers beside `far_field_weights()`, how to implement them if the location of source is unknown? Furthermore, for some Beamformers, interference is required, which confused me since in my case there is only additive white noise instead of source as interference. 
I'm thinking that maybe I should set a distance manually to locate the source, as followed, but it turned out that the distance I set affected the SNR of beamformed signal significantly. Therefore, I want to make sure if there's a better way to deal with this problem!
<pre><code>r = 5
source = pra.SoundSource([r * np.cos(DoA), r * np.sin(DoA)])
</code></pre>

**Comment by haha010508** [comment]
I have the same problem? so i want to know, do you find the method for this?
