### ISSUE TITLE
Could not build wheels for pyroomacoustics which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by ShreJais** [LCAV/pyroomacoustics#184]
After formating and reinstalling windows10 , i install Anaconda3-2020.07-Windows-x86_64 and then trying to install pyroomacoustics using anaconda command prompt generate error :
Collecting pyroomacoustics
  Downloading pyroomacoustics-0.4.1.tar.gz (1.0 MB)
     |████████████████████████████████| 1.0 MB 547 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy in c:\users\shrej\anaconda3\lib\site-packages (from pyroomacoustics) (1.18.5)
Requirement already satisfied: scipy>=0.18.0 in c:\users\shrej\anaconda3\lib\site-packages (from pyroomacoustics) (1.5.0)
Requirement already satisfied: pybind11>=2.2 in c:\users\shrej\anaconda3\lib\site-packages (from pyroomacoustics) (2.5.0)
Requirement already satisfied: Cython in c:\users\shrej\anaconda3\lib\site-packages (from pyroomacoustics) (0.29.21)
Building wheels for collected packages: pyroomacoustics
  Building wheel for pyroomacoustics (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\shrej\anaconda3\python.exe' 'C:\Users\shrej\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\shrej\AppData\Local\Temp\tmprczv5gug'
       cwd: C:\Users\shrej\AppData\Local\Temp\pip-install-wxb_q6vy\pyroomacoustics
  Complete output (87 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\pyroomacoustics
  copying pyroomacoustics\acoustics.py -> build\lib.win-amd64-3.8\pyroomacoustics
  copying pyroomacoustics\beamforming.py -> build\lib.win-amd64-3.8\pyroomacoustics
  copying pyroomacoustics\metrics.py -> build\lib.win-amd64-3.8\pyroomacoustics
  copying pyroomacoustics\multirate.py -> build\lib.win-amd64-3.8\pyroomacoustics
  copying pyroomacoustics\parameters.py -> build\lib.win-amd64-3.8\pyroomacoustics
  copying pyroomacoustics\recognition.py -> build\lib.win-amd64-3.8\pyroomacoustics
  copying pyroomacoustics\room.py -> build\lib.win-amd64-3.8\pyroomacoustics
  copying pyroomacoustics\soundsource.py -> build\lib.win-amd64-3.8\pyroomacoustics
  copying pyroomacoustics\sync.py -> build\lib.win-amd64-3.8\pyroomacoustics
  copying pyroomacoustics\utilities.py -> build\lib.win-amd64-3.8\pyroomacoustics
  copying pyroomacoustics\version.py -> build\lib.win-amd64-3.8\pyroomacoustics
  copying pyroomacoustics\windows.py -> build\lib.win-amd64-3.8\pyroomacoustics
  copying pyroomacoustics\__init__.py -> build\lib.win-amd64-3.8\pyroomacoustics
  creating build\lib.win-amd64-3.8\pyroomacoustics\doa
  copying pyroomacoustics\doa\cssm.py -> build\lib.win-amd64-3.8\pyroomacoustics\doa
  copying pyroomacoustics\doa\detect_peaks.py -> build\lib.win-amd64-3.8\pyroomacoustics\doa
  copying pyroomacoustics\doa\doa.py -> build\lib.win-amd64-3.8\pyroomacoustics\doa
  copying pyroomacoustics\doa\frida.py -> build\lib.win-amd64-3.8\pyroomacoustics\doa
  copying pyroomacoustics\doa\grid.py -> build\lib.win-amd64-3.8\pyroomacoustics\doa
  copying pyroomacoustics\doa\music.py -> build\lib.win-amd64-3.8\pyroomacoustics\doa
  copying pyroomacoustics\doa\plotters.py -> build\lib.win-amd64-3.8\pyroomacoustics\doa
  copying pyroomacoustics\doa\srp.py -> build\lib.win-amd64-3.8\pyroomacoustics\doa
  copying pyroomacoustics\doa\tools_fri_doa_plane.py -> build\lib.win-amd64-3.8\pyroomacoustics\doa
  copying pyroomacoustics\doa\tops.py -> build\lib.win-amd64-3.8\pyroomacoustics\doa
  copying pyroomacoustics\doa\utils.py -> build\lib.win-amd64-3.8\pyroomacoustics\doa
  copying pyroomacoustics\doa\waves.py -> build\lib.win-amd64-3.8\pyroomacoustics\doa
  copying pyroomacoustics\doa\__init__.py -> build\lib.win-amd64-3.8\pyroomacoustics\doa
  creating build\lib.win-amd64-3.8\pyroomacoustics\adaptive
  copying pyroomacoustics\adaptive\adaptive_filter.py -> build\lib.win-amd64-3.8\pyroomacoustics\adaptive
  copying pyroomacoustics\adaptive\data_structures.py -> build\lib.win-amd64-3.8\pyroomacoustics\adaptive
  copying pyroomacoustics\adaptive\lms.py -> build\lib.win-amd64-3.8\pyroomacoustics\adaptive
  copying pyroomacoustics\adaptive\rls.py -> build\lib.win-amd64-3.8\pyroomacoustics\adaptive
  copying pyroomacoustics\adaptive\subband_lms.py -> build\lib.win-amd64-3.8\pyroomacoustics\adaptive
  copying pyroomacoustics\adaptive\util.py -> build\lib.win-amd64-3.8\pyroomacoustics\adaptive
  copying pyroomacoustics\adaptive\__init__.py -> build\lib.win-amd64-3.8\pyroomacoustics\adaptive
  creating build\lib.win-amd64-3.8\pyroomacoustics\transform
  copying pyroomacoustics\transform\dft.py -> build\lib.win-amd64-3.8\pyroomacoustics\transform
  copying pyroomacoustics\transform\stft.py -> build\lib.win-amd64-3.8\pyroomacoustics\transform
  copying pyroomacoustics\transform\__init__.py -> build\lib.win-amd64-3.8\pyroomacoustics\transform
  creating build\lib.win-amd64-3.8\pyroomacoustics\experimental
  copying pyroomacoustics\experimental\deconvolution.py -> build\lib.win-amd64-3.8\pyroomacoustics\experimental
  copying pyroomacoustics\experimental\delay_calibration.py -> build\lib.win-amd64-3.8\pyroomacoustics\experimental
  copying pyroomacoustics\experimental\localization.py -> build\lib.win-amd64-3.8\pyroomacoustics\experimental
  copying pyroomacoustics\experimental\measure_ir.py -> build\lib.win-amd64-3.8\pyroomacoustics\experimental
  copying pyroomacoustics\experimental\physics.py -> build\lib.win-amd64-3.8\pyroomacoustics\experimental
  copying pyroomacoustics\experimental\point_cloud.py -> build\lib.win-amd64-3.8\pyroomacoustics\experimental
  copying pyroomacoustics\experimental\rt60.py -> build\lib.win-amd64-3.8\pyroomacoustics\experimental
  copying pyroomacoustics\experimental\signals.py -> build\lib.win-amd64-3.8\pyroomacoustics\experimental
  copying pyroomacoustics\experimental\__init__.py -> build\lib.win-amd64-3.8\pyroomacoustics\experimental
  creating build\lib.win-amd64-3.8\pyroomacoustics\datasets
  copying pyroomacoustics\datasets\base.py -> build\lib.win-amd64-3.8\pyroomacoustics\datasets
  copying pyroomacoustics\datasets\cmu_arctic.py -> build\lib.win-amd64-3.8\pyroomacoustics\datasets
  copying pyroomacoustics\datasets\google_speech_commands.py -> build\lib.win-amd64-3.8\pyroomacoustics\datasets
  copying pyroomacoustics\datasets\timit.py -> build\lib.win-amd64-3.8\pyroomacoustics\datasets
  copying pyroomacoustics\datasets\utils.py -> build\lib.win-amd64-3.8\pyroomacoustics\datasets
  copying pyroomacoustics\datasets\__init__.py -> build\lib.win-amd64-3.8\pyroomacoustics\datasets
  creating build\lib.win-amd64-3.8\pyroomacoustics\bss
  copying pyroomacoustics\bss\auxiva.py -> build\lib.win-amd64-3.8\pyroomacoustics\bss
  copying pyroomacoustics\bss\common.py -> build\lib.win-amd64-3.8\pyroomacoustics\bss
  copying pyroomacoustics\bss\fastmnmf.py -> build\lib.win-amd64-3.8\pyroomacoustics\bss
  copying pyroomacoustics\bss\ilrma.py -> build\lib.win-amd64-3.8\pyroomacoustics\bss
  copying pyroomacoustics\bss\sparseauxiva.py -> build\lib.win-amd64-3.8\pyroomacoustics\bss
  copying pyroomacoustics\bss\trinicon.py -> build\lib.win-amd64-3.8\pyroomacoustics\bss
  copying pyroomacoustics\bss\__init__.py -> build\lib.win-amd64-3.8\pyroomacoustics\bss
  creating build\lib.win-amd64-3.8\pyroomacoustics\denoise
  copying pyroomacoustics\denoise\iterative_wiener.py -> build\lib.win-amd64-3.8\pyroomacoustics\denoise
  copying pyroomacoustics\denoise\spectral_subtraction.py -> build\lib.win-amd64-3.8\pyroomacoustics\denoise
  copying pyroomacoustics\denoise\subspace.py -> build\lib.win-amd64-3.8\pyroomacoustics\denoise
  copying pyroomacoustics\denoise\__init__.py -> build\lib.win-amd64-3.8\pyroomacoustics\denoise
  creating build\lib.win-amd64-3.8\pyroomacoustics\phase
  copying pyroomacoustics\phase\gl.py -> build\lib.win-amd64-3.8\pyroomacoustics\phase
  copying pyroomacoustics\phase\__init__.py -> build\lib.win-amd64-3.8\pyroomacoustics\phase
  copying pyroomacoustics\build_rir.pyx -> build\lib.win-amd64-3.8\pyroomacoustics
  creating build\lib.win-amd64-3.8\pyroomacoustics\data
  copying pyroomacoustics\data\materials.json -> build\lib.win-amd64-3.8\pyroomacoustics\data
  running build_ext
  cythoning pyroomacoustics/build_rir.pyx to pyroomacoustics\build_rir.c
  building 'pyroomacoustics.libroom' extension
  C:\Users\shrej\AppData\Local\Temp\pip-build-env-3v_dqluq\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\shrej\AppData\Local\Temp\pip-install-wxb_q6vy\pyroomacoustics\pyroomacoustics\build_rir.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for pyroomacoustics
Failed to build pyroomacoustics
ERROR: Could not build wheels for pyroomacoustics which use PEP 517 and cannot be installed directly.

Before reinstalling windows10, i use Anaconda3-2019.07-Windows-x86_64 in which i m able to install pyroomacoustics using command prompt but not able to import pyroomacoustics. But after some when i install each of the requirements individually it worked. 
Please help regarding these issues.

**Comment by fakufaku** [comment]
It seems you figured this out, but here the key was probably to install the compiler required to install the package.

> error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
