### ISSUE TITLE
set_air_absorption question

### ISSUE THREAD

**Issue by opasquetdotfr** [LCAV/pyroomacoustics#191]
Hello !

I am trying to change 'set_air_absorption'.
Should I simply use:
`room.set_air_absorption("0.0001, 0.0003, 0.0006, 0.001, 0.0019, 0.0058, 0.020300000000000002")`

If so, I get the error:
`File "XXX/pyroomacoustics/room.py", line 942, in set_air_absorption
self.air_absorption = self.physics().get_air_absorption()
TypeError: 'Physics' object is not callable`

I instead use:
`room.air_absorption = [x., x., x., x., x., x., x.]`
for "center_freqs": [125, 250, 500, 1000, 2000, 4000, 8000]

I am trying to do something that sounds different than a natural air reverb. My dream would be negative air absorption factors. So I am playing with parameters such as extreme speeds of sound etc. If you have an idea of which params I could play with...

Thank you very much !!

O.

**Comment by jvietorisz** [comment]
Hello,

I am getting the same error in a more simple case, where I am interested in setting a single constant absorption coefficient (to mimic sound waves propagating through shallow water). Was this backend issue ever resolved? Thanks!

**Comment by fakufaku** [comment]
@opasquetdotfr @jvietorisz sorry this took so long, the bug is now corrected.
