### ISSUE TITLE
why compute spatial spectrum like this in MUSIC

### ISSUE THREAD

**Issue by Ryuk17** [LCAV/pyroomacoustics#204]
In the [music.py](https://github.com/LCAV/pyroomacoustics/blob/master/pyroomacoustics/doa/music.py), the spatial spectrum is computed like this 
```
    # compute spatial spectrum
    identity = np.zeros((self.num_freq, self.M, self.M))
    identity[:, list(np.arange(self.M)), list(np.arange(self.M))] = 1
    cross = identity - np.matmul(Es, np.moveaxis(np.conjugate(Es), -1, -2))

```
But I cannot find the corresponding equation in the paper _Multiple emitter location and signal parameter estimation_
I will be appreciate if you solve my confusion，thanks

**Comment by Womac** [comment]
@Ryuk17 in MUSIC, the noise subspace is used - which is computed here via cross. An identity matrix is full rank with all eigenvalues 1. In a PSD matrix, as it is hermetian, all Eigenvectors are orthogonal. Via `np.matmul(Es, np.moveaxis(np.conjugate(Es), -1, -2))` you compute a matrix presenting the signal subspace [typically not full rank]. By `identity - np.matmul(Es, np.moveaxis(np.conjugate(Es), -1, -2))` you compute the noise subspace as the signal subspace is subtracted of a full-rank matrix [and the respective 'eigenvalues' are all 1].

**Comment by Ryuk17** [comment]
Thanks for your explaination.  It means that the not full rank matrix will lead to a wrong result in MUSIC.

**Comment by fakufaku** [comment]
@Ryuk17 The matrix is expected to be rank deficient. For MUSIC, we want to find vectors that are in the signal subspace, i.e. whose projection into the noise subspace has a small norm. The matrix `cross` above projects the vectors into the noise subspace.

**Comment by Ryuk17** [comment]
I got it, thanks!
