### ISSUE TITLE
Cannot import name 'libroom' from 'pyroomacoustics'

### ISSUE THREAD

**Issue by dgutierrezATC** [LCAV/pyroomacoustics#208]
Hi guys,

I have tried to install the package and to run an example on Windows10. I created a virtual environment with Python3.5, and then I installed the package.
When I tried to run the example code, I got this error:

`Traceback (most recent call last):
  File "d:/Universidad/Repositorios/GitHub/pyroomacoustics/sandboyx.py", line 3, in <module>
    import pyroomacoustics as pra
  File "d:\Universidad\Repositorios\GitHub\pyroomacoustics\pyroomacoustics\__init__.py", line 120, in <module>
    from . import libroom as libroom
ImportError: cannot import name 'libroom'`

Do you have any idea about what I am doing wrong?

Many thanks in advance!

**Comment by fakufaku** [comment]
I think this may happen if the working directory is the root of the pyroomacoustics repo. Can you try to run your script from somewhere else ?

**Comment by fakufaku** [comment]
Also, did you install the package via pypi ?

**Comment by dgutierrezATC** [comment]
It was because of the first thing you have mentioned! Many thanks! :D
