### ISSUE TITLE
Concatenating beamformed output WAVs

### ISSUE THREAD

**Issue by CJai-K** [LCAV/pyroomacoustics#212]
Hi,
I'm working on a project to beamform mic input in real time. I'm assuming a real situation where to source will be moving so I use far field weights without specifying the distance from the mic.

I process the audio in chunks and simply use np.concatenate to combine them, but I hear a period of silence between clips that scales with my setting of number of weights/filter length.

Could I get a little more insight into this behavior and a way to work around it if possible? Thanks in advanced!

Update: I removed FFT//2 from either end of the output and this solves the gap issue and the rest of the audio appears intact, but is this a valid approach?

**Comment by fakufaku** [comment]
Hi, I assume you are doing the filtering in the time-domain (but something similar may happen in frequency domain).
If your block size is B and the filter size is L, then the output of the convolution is B + L - 1. So the blocks that you are concatenating back together are slightly longer than originally. It is like you added zeros between the blocks.
What you are looking for is [overlap-add convolution](https://en.wikipedia.org/wiki/Overlap%E2%80%93add_method).
You should overlap the bit that extends out of the block and sum it with the beginning of the next block.

**Comment by fakufaku** [comment]
(I close the issue because it is not pyroomacoustics related, feel free to respond regardless)
