### ISSUE TITLE
Echo simulation

### ISSUE THREAD

**Issue by yyf17** [LCAV/pyroomacoustics#218]
Hi there,
I want to know any way to simulate a signal source at a certain position in the room, and then how to obtain the echo of this signal source at that position.
Thanks

**Comment by scrolller** [comment]
Hi,

That is an interesting request. What project are you working on, I think we might share similar goals.

**Comment by fakufaku** [comment]
Hi @yyf17 , @scrolller ,
What do you mean by the echo ? If you mean the room impulse response, then you could take a look at some of the example scripts, such as [this one](https://github.com/LCAV/pyroomacoustics/blob/master/examples/room_from_rt60.py).

**Comment by yyf17** [comment]
@fakufaku thank you. Yes,I mean he room impulse response.
