### ISSUE TITLE
A little question about the AuxIVA blind source separation algorithm

### ISSUE THREAD

**Issue by Zyy438** [LCAV/pyroomacoustics#219]
I am curious whether the AuxIVA algorithm can tell the specific input sound source that an output is corresponding to? I have tons of audio files so I think I can not link them manually.
Thanks！ 😊

**Comment by fakufaku** [comment]
Hi @Zyy438 , 
I am not sure I understand the question. IVA can separate sounds that have been mixed together, if provided with multi-channel recordings. However, IVA does not guarantee any ordering of the sources after the separation. So if you want to compare to some sort of originals, you need to try all the combinations to find which output correspond to which source.
Is this what you meant ?

**Comment by Zyy438** [comment]
Yes thats what i mean~ Sorry for the poor English expression hhaha 
and thank you very much for the help! I think i have to compare them by myself

**Comment by fakufaku** [comment]
No worries :)
Let's say you can compute the error between the source `s` and an estimate `u` using the function `error(s, u)`, then you first compute the cost matrix `C` with
```
C_{ij} = error(s_i, u_j)
```
and then find the permutation `p(j)` of the indices that minimizes the sum
```
\sum_i C_{i,p(i)}
```
using the `llinear_sum_assignment` [function from scipy](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.optimize.linear_sum_assignment.html).
This will give you the permutation of output sources with the least total cost.
Now, if you are just looking for the SI-SDR, you can use [this implementation](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.optimize.linear_sum_assignment.html).

**Comment by Zyy438** [comment]
Thank you, that will be so useful for me! 😊
I am now combining the delay-sum beamforming and BSS together to try to get a better-enhanced signal. The process is like this:
![process](https://user-images.githubusercontent.com/73535458/115406371-b0471100-a221-11eb-80a0-8b628f2115a1.jpg)

So, I think the error function you provided will be also useful to measure whether this combination works or not. Thank you so much!
