### ISSUE TITLE
Python error: deallocating None

### ISSUE THREAD

**Issue by FrancoisGrondin** [LCAV/pyroomacoustics#22]
Hi,

First, let me thank you for sharing this great tool with the community. I'm using the room impulse response tool to generate a large amount of RIRs to perform data augmentation. Each time I run my script, I get this error at the 19208th call of the function `compute_rir()`:

```
Current thread 0x00007f0e73bf3700 (most recent call first):
  File "[...]/.local/lib/python3.5/site-packages/numpy/core/_internal.py", line 477 in Stream
  File "[...]/.local/lib/python3.5/site-packages/numpy/core/_internal.py", line 449 in _dtype_from_pep3118
  File "[...]/.local/lib/python3.5/site-packages/numpy/ctypeslib.py", line 436 in as_array
  File "/usr/local/lib/python3.5/dist-packages/pyroomacoustics/room.py", line 652 in image_source_model
  File "/usr/local/lib/python3.5/dist-packages/pyroomacoustics/room.py", line 683 in compute_rir
  File "/usr/local/lib/python3.5/dist-packages/pydsp/simulator.py", line 33 in rir
  File "../batches/rooms_simultator.py", line 67 in <module>
  Fatal Python error: deallocating None
```
From my understanding, this error might be due to bad deallocation of memory in the C/C++ routine (I know pyroom uses C optimized code to generate RIR faster). Have you ever encounter this issue before?

Thank you,

**Comment by fakufaku** [comment]
Hi François, I am very happy to hear that this is being useful! And thanks for letting me know about the bug. I haven't encountered this error before, but have probably not called `compute_rir()` on the same object so many times! 😄 
It might help to know which kind of OS you are using. And I am guessing that in your script you are first creating a `Room` and then keep moving the source and microphones to produce new rirs. Is that correct ?
It seems indeed the reference count in the C code might be responsible for this type of error and I will look into it.

**Comment by FrancoisGrondin** [comment]
Thank you for this quick reply! Yes I'm using it a lot, thanks to deep learning :P

I'm currently running Ubuntu 16.04, and Python 3.5.2. Here is an example of what I do:

```
def foo(<room dimensions>,<absorption coeff>,<sample rate>,<sources positions>,<mics positions>):

		shoebox = pyroomacoustics.ShoeBox(
			<room dimensions>,
			absorption = <absorption coeff>,
			fs = <sample rate>,
			max_order = 15)

		for iSrc in range(0, nSrcs):
			shoebox.add_source(<source position>)

		shoebox.add_microphone_array(pyroomacoustics.MicrophoneArray(<mics positions>.T,fs))

		shoebox.compute_rir()
```

I select a random room dimension, and for each room with these dimensions, I generate 100 RIRs. However, I will call foo 100 times with the same room dimensions, but different mics and sources positions, such that the ShoeBox constructor and compute_rir() are called everytime.

Thank you for your quick feedback!

**Comment by fakufaku** [comment]
Thanks for the details. I'm trying to see if the bug happens for a test case I wrote based on this template.

I am also aware that I am doing some sketchy things with memory allocation in the C extension. I will try to fix this, but it might take a few days. Please hang on.

**Comment by FrancoisGrondin** [comment]
Thank you! Don't worry, I know what it is when you code in C. It's always a long process. Have you tried profiling with valgrind yet? It might give you good insides if there are memory leaks or double free.

**Comment by fakufaku** [comment]
Hi François, seems the issue was less complex to fix than I expected. I have pushed a fix to branch `bugfix_proper_C_mem_management`. Do you think you could try it out ? To do that, do the following:

    git clone https://github.com/LCAV/pyroomacoustics.git
    cd pyroomacoustics
    git checkout bugfix_proper_C_mem_management
    python setup.py build_ext --inplace

Then run your script with python path pointing to the local pyroomacoustics repo.

    export PYTHONPATH=/path/to/pyroomacoustics:$PYTHONPATH
    python /path/to/my/script

If the result is positive, I'll push the bugfix in release. Thanks!

**Comment by FrancoisGrondin** [comment]
Thank you!

I'm refactoring my library, so as soon as I can run my script again, I'll test this and give you feedback! Thanks a lot!

**Comment by fakufaku** [comment]
Thanks! Because I could write my own unit test for this and check it failed before and doesn't fail with bugfix, I'm pretty sure _something_ was fixed. So I pushed a new release (0.1.17). So no need to go through the procedure above, just upgrade through pip (if that is what you use).

I'll close that for now, but feel free to reopen it in case it didn't actually fix the problem.
