### ISSUE TITLE
channel order about circular array

### ISSUE THREAD

**Issue by Ryuk17** [LCAV/pyroomacoustics#221]
I use `R = pra.circular_2D_array([4, 4], 4, np.pi/2, 0.05)` to place a circular microphone and save the sound generated by pyroomacoustics with
`room.mic_array.to_wav(
    "./sample/circular/mix.wav",
    norm=True,
    bitdepth=np.int16,
)`
Now, I have a four-channel audio, could you please tell me which microphone below is consistant with channel 0 of mix.wav. Thanks in advance.
![image](https://user-images.githubusercontent.com/22525811/119116703-17432a00-ba5b-11eb-9249-370104201c96.png)

**Comment by fakufaku** [comment]
Hi @Ryuk17 , the output channels are stored in the rows of `room.mic_array.signals`. The order of the channels corresponds to the order of the microphone locations stored in the columns of `room.mic_array.R`, which would be the columns of `R` in your example above.
If I remember correctly, the `circular_2D_array` function will produce the microphone locations in trigonometric order, i.e., counter-clockwise, as in your picture.
