### ISSUE TITLE
smaller reverberation time

### ISSUE THREAD

**Issue by IFICL** [LCAV/pyroomacoustics#233]
Hi, I wonder whether I can set up a smaller RT60 for the Shoebox room. When I try to use the ` rt60_tgt = 0.1  # seconds room_dim = [4, 7, 2.8] # meters`  to generate audio, I will get the error that `ValueError: evaluation of parameters failed. room may be too large for required RT60.`. 

How can I deal with it if I want to set lower rt60 while not changing my room setup?

**Comment by fakufaku** [comment]
Hi @IFICL , the computation of the absorption and maximum order is based on [Sabine's formula](https://en.wikipedia.org/wiki/Reverberation). The code is [here](https://github.com/LCAV/pyroomacoustics/blob/master/pyroomacoustics/acoustics.py#L522).

Given a room dimensions, we reverse the formula to obtain the average absorption coefficient as follows
```python
e_absorption = (
        sab_coef * np.log(10) * V / (c * S * rt60)
    )  # absorption in power (sabine)
```
Physically, `e_absorption` needs to be a number between 0 and 1. However, it is possible for the formula to give numbers that are larger than one for some room dimensions. This is what happens here. You need to make the room a little bit smaller.

If you don't care about physical plausibility, you could reduce the maximum order, or just truncate the impulse response to the desired length.

**Comment by fakufaku** [comment]
If you want to simulate anechoic signals (i.e., RT60 = 0), the easiest solution is to use `max_order=0`.

If you want a short impulse response, e.g. RT60 = 100 ms, then you should set a higher `energy_absorption`. I have successfully created RIR with 50 ~ 100 ms RT60, so it should be possible. Note that setting `e_absorption=1` will result in anechoic response (no reverberation at all) because all the sound will be absorbed at the first reflection.

**Comment by fakufaku** [comment]
So the desired RT60 and values obtained from inverting Sabine's formula are not guaranteed to produce the correct RT60. This is why they might be different. The correct one is the measured one. The idea of using the inverse Sabine's formula is to sort of get in the ball park of the desired RT60. Not that some parameter values may also affect the RT60. For example if `max_order` is too short, then the RIR produced will be shorter too. If in doubt, use a larger value of `max_order`.
