### ISSUE TITLE
Run time error in CentOS

### ISSUE THREAD

**Issue by stonelazy** [LCAV/pyroomacoustics#239]
# Issue
Pyroomacoustics work fine in Ubuntu OS, but when installing this in CentOS servers the below error gets thrown.

# Installation procedure followed for installing Pyroom. 
Tried installing through two different ways. 
1.) `pip install pyroomacoustics`.  
2.) `pip install git+https://github.com/LCAV/pyroomacoustics`. 
Facing issue with both the methods.

# Exception Trace
```
from pyroomacoustics import Beamformer, Room
/opt/app-root/src/miniconda3/envs/env1/lib/python3.8/site-packages/pyroomacoustics/__init__.py:123: in <module>
    from . import libroom as libroom
E   ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/app-root/src/miniconda3/envs/env1/lib/python3.8/site-packages/pyroomacoustics/libroom.cpython-38-x86_64-linux-gnu.so)

```

# Steps taken to fix this issue. 
1.) Tried installing directly using the Github repo link so that it gets built in my destination machine thereby resolving the dependencies on its own, but still facing the same issue.  
2.) Tried building this locally using [docs reference](https://pyroomacoustics.readthedocs.io/en/pypi-release/contributing.html#develop-locally) but still having same issue.

# Environment
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC)
ldd (GNU libc) 2.17
Python version - 3.8

# Note
Am aware Pyroom supports only until 3.7 but the trace didn't look like it was incompatible for 3.8.

**Comment by fakufaku** [comment]
That's pretty strange, I am regularly using pyroomacoustics on centos 7 without such problem.

Here are my system specs.
```bash
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.7.1908 (Core)
Release:        7.7.1908
Codename:       Core
```

I use conda to create the environment
```bash
$ conda create -n pyroom_test python=3.8
$ conda activate pyroom_test
```

Then I install pyroomacoustics with pip.
```bash
$ python -m pip install --no-cache-dir pyroomacoustics
Collecting pyroomacoustics
  Downloading pyroomacoustics-0.5.0.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 34.3 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting Cython
  Downloading Cython-0.29.24-cp38-cp38-manylinux1_x86_64.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 114.8 MB/s
Collecting numpy
  Downloading numpy-1.21.4-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
     |████████████████████████████████| 15.7 MB 115.7 MB/s
Collecting pybind11>=2.2
  Downloading pybind11-2.8.1-py2.py3-none-any.whl (208 kB)
     |████████████████████████████████| 208 kB 127.2 MB/s
Collecting scipy>=0.18.0
  Downloading scipy-1.7.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (39.3 MB)
     |████████████████████████████████| 39.3 MB 121.6 MB/s
Building wheels for collected packages: pyroomacoustics
  Building wheel for pyroomacoustics (PEP 517) ... done
  Created wheel for pyroomacoustics: filename=pyroomacoustics-0.5.0-cp38-cp38-linux_x86_64.whl size=8626958 sha256=99b795ba9b6029eec1234b1b3f00adcea2ec8fe69a648b57f315dc8a18fd6974
  Stored in directory: /tmp/pip-ephem-wheel-cache-aatcjm43/wheels/60/a6/13/3ccfa769ebfe55c019d1bb784509ff419c0a9d41f3bc51da26
Successfully built pyroomacoustics
Installing collected packages: numpy, scipy, pybind11, Cython, pyroomacoustics
Successfully installed Cython-0.29.24 numpy-1.21.4 pybind11-2.8.1 pyroomacoustics-0.5.0 scipy-1.7.2

$ python
Python 3.8.12 (default, Oct 12 2021, 13:49:34)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyroomacoustics as pra
>>> print(pra.__version__)
0.5.0
```

As you may notice above, the default version of GCC on CentOS is pretty old (4.8.5), but you used a more recent one (8.3.1). How did you install the newer one ? Is it possible this is the cause of the problem ? CentOS also allows to use a more modern version of GCC (7.3.1) that I also tried with the same result (i.e., no problem).

We are currently supporting from Python 3.6 to 3.9.

**Comment by stonelazy** [comment]
> Is it possible this is the cause of the problem ?  

Default GCC installed in my image was also same as yours, 4.8.5. Doubting if this pretty old version could be a problem i upgraded it myself using one of their mirrors site. https://mirrors.concertpass.com/gcc/releases/gcc-9.2.0/gcc-9.2.0.tar.gz So i had actually tested both in older and latest version and i had the same issue.     

After your confirmation that this actually works in CentOS, i went on to try with a fresh container & image but i was still able to reproduce the issue. However, i guess i have cornered down the issue to be this - import order of pyroomacoustics library.  If i import pra before torch, i don't seem to have any issue otherwise this error gets thrown.    

> (env1) bash-4.2# python.   

Python 3.8.12 (default, Oct 12 2021, 13:49:34)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
```
import torch
import pyroomacoustics #this code throws error because pra is imported after torch

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/app-root/src/miniconda3/envs/env1/lib/python3.8/site-packages/pyroomacoustics/__init__.py", line 123, in <module>
    from . import libroom as libroom
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/app-root/src/miniconda3/envs/env1/lib/python3.8/site-packages/pyroomacoustics/libroom.cpython-38-x86_64-linux-gnu.so)
```

If pra is imported before pytorch, it works without any issues.     

```
import pyroomacoustics
import torch
print(pyroomacoustics.__version__)
0.5.0
```
(env1) bash-4.2#  gcc --version
gcc (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by fakufaku** [comment]
I'm sorry but I don't really know what's going on there. I have also been using pytorch together with pyroomacoustics and did not run into such problems. I have quickly checked that this is not the case with the latest version of pyroomacoustics either. I paste below a conda environment file that I am using.

```yaml
name: pyroomtestenv
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch>=1.9.0
  - cudatoolkit=10.2
  - numpy
  - scipy>=1.5.0
  - matplotlib
  - pip
  - pip:
      - pyroomacoustics
```

Maybe if you could share a minimal container file with the problems that could help debug.

**Comment by stonelazy** [comment]
Thanks for getting back on this quick.   
Please find the list of commands that i have executed to reproduce this issue. 
Name of docker image - scarecrow1123/centos7-python
```
sudo docker pull scarecrow1123/centos7-python
sudo docker run -it cc17756936ee #cc17756936ee is the image id
conda create -n pyroom_test python=3.8 -y
conda activate pyroom_test
pip install torch
python -m pip install --no-cache-dir pyroomacoustics
> python
import torch
import pyroomacoustics
<Now error should get thrown>
```

My conda environment (After installing just torch and pra)
```
(pyroom_test) bash-4.2# conda list
# packages in environment at /opt/app-root/src/miniconda3/envs/pyroom_test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             4.5                       1_gnu
ca-certificates           2021.10.26           h06a4308_2
certifi                   2021.10.8        py38h06a4308_0
cython                    0.29.24                  pypi_0    pypi
ld_impl_linux-64          2.35.1               h7274673_9
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.3.0               h5101ec6_17
libgomp                   9.3.0               h5101ec6_17
libstdcxx-ng              9.3.0               hd4cf53a_17
ncurses                   6.3                  h7f8727e_2
numpy                     1.21.4                   pypi_0    pypi
openssl                   1.1.1l               h7f8727e_0
pip                       21.2.4           py38h06a4308_0
pybind11                  2.8.1                    pypi_0    pypi
pyroomacoustics           0.5.0                    pypi_0    pypi
python                    3.8.12               h12debd9_0
readline                  8.1                  h27cfd23_0
scipy                     1.7.2                    pypi_0    pypi
setuptools                58.0.4           py38h06a4308_0
sqlite                    3.36.0               hc218d9a_0
tk                        8.6.11               h1ccaba5_0
torch                     1.10.0                   pypi_0    pypi
typing-extensions         4.0.0                    pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1
xz                        5.2.5                h7b6447c_0
zlib                      1.2.11               h7b6447c_3
```

**Comment by fakufaku** [comment]
Hum, I'm not really sure what's going on.

* It seems that you are using devtoolset-4 which comes with GCC-5
* You are using conda but getting torch from pypi

I think there is some kind of mismatch between your version of torch and the compiler installed or some mixup in the shared libraries. At first glance it does not seem that the problem is on pyroomacoustics side since you are compiling locally and it works when you are not using torch.

Pytorch is also distributing conda packages so you may be more lucky with these.

**Comment by stonelazy** [comment]
Thanks you for your input on this. Will get back once have identified the issue.

**Comment by stonelazy** [comment]
Tried your suggestion of installing pytorch through conda dist and i wasn't able to reproduce the issue i.e, everything works no matter how i import. Thanks for your prompt replies that helped this issue.
