### ISSUE TITLE
The speech output of the simulation has DC bias

### ISSUE THREAD

**Issue by laizp-black** [LCAV/pyroomacoustics#244]
Hello, I used the speech simulation method in the [document](https://pyroomacoustics.readthedocs.io/en/pypi-release/pyroomacoustics.room.html#full-example), but the output voice there is DC offset what is the problem.

**Comment by fakufaku** [comment]
Hi @laizp-black , this means that your input speech also has DC offset. You can get rid of it by subtracting the mean from the inputs signal from itself.
