### ISSUE TITLE
Adaptive filtering in STFT domain example seems broken. 

### ISSUE THREAD

**Issue by popcornell** [LCAV/pyroomacoustics#275]
Here https://github.com/LCAV/pyroomacoustics/blob/b7323354b82d292d12850d59eef831fef491b25d/examples/adaptive_filter_stft_domain.py#L84

smth like this should do the trick 
```python 
 time_indx = 0
 for n in range(num_blocks):
       # update filter with new samples
       adaptive_filters.update(X_concat[:, n], Y_concat[:, n])
       aec_out[time_indx: time_indx + hop] = stft_out.synthesis(Y_concat[:, n] - np.diag(np.dot(adaptive_filters.W.conj().T, adaptive_filters.X)))
       time_indx += hop
```

**Comment by fakufaku** [comment]
Thanks for reporting! Though it seems to work for me. Could you please share the python and pyroomacoustics versions ? Possibly numpy version too ? Also if there is an error, could you please also share its content ?

I get this output.
![image](https://user-images.githubusercontent.com/1118133/188037735-f55536eb-428a-49be-8289-95348d185563.png)

**Comment by popcornell** [comment]
I think the `error_per_band` variable is fine the problem lies in the `aec_output` time domain signal. The script runs fine also for me but if you look at this latter it is mostly zeros

**Comment by fakufaku** [comment]
@popcornell I see the problem now. The variable `n` increments by one, but we want to increment it by `hop`. I will fix this. Thanks!

**Comment by fakufaku** [comment]
I fixed the bug in PR #277 . Could you please take a look ?

**Comment by popcornell** [comment]
it looks good to me !

**Comment by popcornell** [comment]
I can close this issue, thanks !
