### ISSUE TITLE
How return receiever location from ID ?

### ISSUE THREAD

**Issue by ppothana** [LCAV/pyroomacoustics#278]
For instance `room.rir[n][0]` returns the RIR array of the nth receiver. Is there any way to get the spacial location of this nth receiver in the room?
Thank you,

**Comment by fakufaku** [comment]
Hi @ppothana , something like `room.mic_array.R[:, n]` shoud do it. Sorry that this is not better documented! 🙈

**Comment by ppothana** [comment]
@fakufaku, Thank you very much !
