### ISSUE TITLE
Your code gives me error

### ISSUE THREAD

**Issue by VijaykumarMangukiya** [LCAV/pyroomacoustics#292]
Hi, I am newbie here, I will learn pyroomacoustics as well as python together, When I am run your code in my Jupyter notebook I got the different types of error, I will try to solved but it takes much time. Can you suggest me how your all code run smoothly without error?

**Comment by fakufaku** [comment]
This was solved on the Discord. The problem was that the source signal was stereo. Making it mono solved the problem.
