### ISSUE TITLE
Colatitude angle usage 360 degree(colatitude <= np.pi and colatitude >= 0)

### ISSUE THREAD

**Issue by ClearVoiceM** [LCAV/pyroomacoustics#298]
Hi,
I'm trying to generate audio 360 degree azimuth and elevation. But pyroomacoustics can support max 180 deg elevation. Is there any way to change elevation(colatitude) angle to support 360 degree. 
example: dir_obj = CardioidFamily(orientation=DirectionVector(azimuth=-90, colatitude=-90, degrees=True), pattern_enum=DirectivityPattern.HYPERCARDIOID)

Thanks

**Comment by fakufaku** [comment]
Hi, sorry for poor response time. Spherical coordinates are defined with azimuth in [0, 360] and colatitude from 0 to 180 degrees (0 being the north pole). This is similar to latitude and longitude on the globe. The ranges are sufficient to describe every point in a non-redundant way.
https://en.wikipedia.org/wiki/Spherical_coordinate_system

**Comment by ClearVoiceM** [comment]
Hi,
Thanks for the answer.

**Comment by ClearVoiceM** [comment]
Hi,
Thanks for the answer.
