### ISSUE TITLE
room.mic_array.to_wav wrong sample rate?

### ISSUE THREAD

**Issue by rorywalsh** [LCAV/pyroomacoustics#307]
I can't seem to get `room.mic_array.to_wav()` to write with the sample rate specified for the room? It always writes at 8kHz? Here is my code:

```
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import wavfile
from scipy.signal import fftconvolve
import scipy as sci
from scipy.fftpack import fft
import pyroomacoustics as pra

corners = np.array([[0,0], [0,3], [5,3], [5,1], [3,1], [3,0]]).T  # [x,y]
room = pra.Room.from_corners(corners)
room.extrude(2.)

fs, signal = wavfile.read("sample44100kHz.wav")
room = pra.Room.from_corners(corners, fs, max_order=3, materials=pra.Material(0.2, 0.15), ray_tracing=True, air_absorption=True)
room.extrude(2., materials=pra.Material(0.2, 0.15))
room.set_ray_tracing(receiver_radius=0.5, n_rays=10000, energy_thres=1e-5)
room.add_source([.1, .1, 0.1], signal=signal)
R = np.array([[0.5], [.2], [0.5]]) # [[x], [y], [z]]
room.add_microphone(R)
room.compute_rir()
room.simulate()

# ir_room3 is always 8kHz? 
room.mic_array.to_wav('ir_room3.wav', norm=True, bitdepth=np.int16)
```

I can get around this by simply writing the contents of `room.mic_array.signals[0]` to file using wavfile.write, but am I'd like to know if I'm missing something here that's causing this issue?

**Comment by fakufaku** [comment]
Hello @rorywalsh , I have just tried your code and it works without issue. The output file has the same sampling frequency as the input file.

Are you sure that `sample44100kHz.wav` is not, in fact, an 8 kHz file ? (also 44100 **k**Hz is a lot of Hertz 😄)
This would be the simplest explanation...

**Comment by rorywalsh** [comment]
You're right that is a **lot** of hertz 😂 I have dicky checked the file and it is definitely 44.1kHz. anyway, if your not experiencing the issue there I'll close this. It's obviously something on my end causing the problem 👍

**Comment by fakufaku** [comment]
Sorry, I didn't mean to negate your experience! I have modified the script to re-read the file and write out the new sampling frequency.

```python
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import wavfile
from scipy.signal import fftconvolve
import scipy as sci
from scipy.fftpack import fft
import pyroomacoustics as pra

corners = np.array([[0, 0], [0, 3], [5, 3], [5, 1], [3, 1], [3, 0]]).T  # [x,y]
room = pra.Room.from_corners(corners)
room.extrude(2.0)

fs, signal = wavfile.read("B3zlo5wV9Vo.2.wav")
print("Input freq:", fs)
room = pra.Room.from_corners(
    corners,
    fs,
    max_order=3,
    materials=pra.Material(0.2, 0.15),
    ray_tracing=True,
    air_absorption=True,
)
room.extrude(2.0, materials=pra.Material(0.2, 0.15))
room.set_ray_tracing(receiver_radius=0.5, n_rays=10000, energy_thres=1e-5)
room.add_source([0.1, 0.1, 0.1], signal=signal)
R = np.array([[0.5], [0.2], [0.5]])  # [[x], [y], [z]]
room.add_microphone(R)
room.compute_rir()
room.simulate()

# ir_room3 is always 8kHz?
room.mic_array.to_wav("B3zlo5wV9Vo.2.rev.wav", norm=True, bitdepth=np.int16)

fs_after, signal_after = wavfile.read("B3zlo5wV9Vo.2.rev.wav")
print("Output freq:", fs)
```
Just the file name is different since I did not have your file.

Which version of pyroomacoustics are  you using ?

**Comment by rorywalsh** [comment]
Don't worry, you've been most helpful. I will try this once I get a chance.

**Comment by fakufaku** [comment]
🙇 

Could you post the file here for me to check ?

**Comment by rorywalsh** [comment]
[sineSweep.zip](https://github.com/LCAV/pyroomacoustics/files/10792049/sineSweep.zip)

Here it is. Btw, you asked about what version of pyroom I'm using, I'm using the latest release afaik.

**Comment by fakufaku** [comment]
Thanks, can you please also post the file produced by pyroomacoustics ?

**Comment by rorywalsh** [comment]
Sure. Here it is.
[sineRev.zip](https://github.com/LCAV/pyroomacoustics/files/10792247/sineRev.zip)

**Comment by fakufaku** [comment]
Ouch, there was a mistake in my script above!!! I was not printing `fs_after` in the final print. I have corrected and tried again and I get the same error as you do now!

**Comment by rorywalsh** [comment]
Ok, we're on the same footing now :)

**Comment by fakufaku** [comment]
Ok, I have identified the problem. You need to provide the sampling frequency as a keyword argument to the `from_corners` method.
```python
room = pra.Room.from_corners(
    corners,
    fs=fs,
    max_order=3,
    materials=pra.Material(0.2, 0.15),
    ray_tracing=True,
    air_absorption=True,
)
```
If you omit the keyword in this case, python automatically infer that you are providing the second **positional** argument of the method, in this case `absorption`. Absorption is a deprecated argument that has been replaced by `materials` and is ignored, which is why there was no apparent warning or problem with the simulation...

The `absorption` argument has been deprecated for a while and I will soon remove it, which will solve the issue altogether. In the meantime, providing `fs=fs` will solve the problem too.

**Comment by rorywalsh** [comment]
Thanks @fakufaku That's makes perfect sense, and also explains why I wasn't seeing this behaviour in other examples. Thanks again for taking the time to look into this 👍
