### ISSUE TITLE
room.simulate error

### ISSUE THREAD

**Issue by chenCFD** [LCAV/pyroomacoustics#318]
when i simulate wth some sources and mics, i encounter the error as below:

File "C:\Users\v003280\Desktop\sound-source-localization\weipeng-he-4mic\run\resnet-eval.py", line 361, in <module>
    room.simulate()

  File "C:\Users\v003280\Anaconda3\lib\site-packages\pyroomacoustics\room.py", line 2449, in simulate
    premix_signals[s, m, d : d + len(sig) + len(h) - 1] += fftconvolve(

ValueError: operands could not be broadcast together with shapes (68727,) (0,) (68727,)

**Comment by fakufaku** [comment]
Hi @chenCFD , this looks like a problem with your input signal or the way the simulation of set up.
I can help if you share the script that produces the error.

**Comment by chenCFD** [comment]
Hi @fakufaku, the problem was solved after making sure input signal is correct.
Thank you for your remind!

**Comment by fakufaku** [comment]
Fantastic, I'll close the issue then.
