### ISSUE TITLE
Speed of sound doesn't seem to be constant

### ISSUE THREAD

**Issue by Archibalde** [LCAV/pyroomacoustics#33]
Hi,

I am currently using pyroomacoustics for delayed & attenuated mixtures in blind source separation. That is an awesome tool. Yet I have a little problem as I found that the speed of sound isn't constant in pyroomacoustics.

How to reproduce:

CODE:
```python

fs, s1 = wavfile.read('/home/felix/Simulation salle/Test reberv = 0,2 et 5 images/ref_1200Hz_pure.wav')

# room dimension
room_dim = [5, 5]

# Create the shoebox
shoebox = pra.ShoeBox(
    room_dim,
    absorption=0.999,
    fs=fs,
    max_order=0,
    )

# source and mic locations
shoebox.add_source([2, 3], signal=s1)

R = np.array([[2,2],[2,1]])
bf = pra.MicrophoneArray(R,shoebox.fs)
shoebox.add_microphone_array(bf)

# run ism
shoebox.simulate()

shoebox.plot()
plt.grid()
plt.show()

audio_reverb = shoebox.mic_array.to_wav('/home/felix/test_reverb.wav', norm=True, bitdepth=np.int16)
```

ILLUSTRATIONS:

![github3](https://user-images.githubusercontent.com/9808326/40883871-56c6045e-6707-11e8-865b-466d4f53b15e.png) (The .wav file I used)
![github1](https://user-images.githubusercontent.com/9808326/40883836-89fb411e-6706-11e8-9067-324149bc791e.png)
![github2](https://user-images.githubusercontent.com/9808326/40883837-8b1283aa-6706-11e8-88cf-24ce19e4770d.png) (The results recorded by pyroomacoustics)

Although the distance between the source and first mic is `d1 = 1 m` and to the second mic is `d2 = 2 m`, the delay I found didn't double (see the screenshot in Audacity). Why is that? It seems wrong to me. (Note that in my example there is no reverberation involved, simply delays)

Thank you!

EDIT : One possibility would be that there is a slight delay at the beginning before my source starts emitting somehow due to pyroomacoustics. That would make more sense.
EDIT2 : That's actually that. I looked at e.g. the delay of arrival between the two mics of a peak, and that is exactly the time needed to propagate through 1 m. This issue helped too ( https://github.com/LCAV/pyroomacoustics/issues/23 ). Sorry for posting too fast... Thanks again, your tool do help me a lot!

**Comment by fakufaku** [comment]
Hi Archibald, there is indeed a 40 samples delay due to the fractional delay filter. Good you could sort it out! Glad it is being useful!
