### ISSUE TITLE
why conj in ILRMA

### ISSUE THREAD

**Issue by MordehayM** [LCAV/pyroomacoustics#346]
Hello,
I don't get why there is conj() on this line:
https://github.com/LCAV/pyroomacoustics/blob/fa064c2b9db39f1245ef22501c63dd4575c8656a/pyroomacoustics/bss/ilrma.py#L162

according to the paper "Determined Blind Source Separation Unifying Independent Vector Analysis and Nonnegative Matrix Factorization", which describes the ILRMA algo, I don't see this conjugate operation. But the input to the variable W should be without conj:
![‏‏לכידה](https://github.com/LCAV/pyroomacoustics/assets/72784862/de9971c5-3952-4ecc-898f-190aade642f3)

It is worth noting that when removing this conj and adding it in this line (as the paper claims):
https://github.com/LCAV/pyroomacoustics/blob/fa064c2b9db39f1245ef22501c63dd4575c8656a/pyroomacoustics/bss/ilrma.py#L112
the algorithm does not work(not converges)

**Comment by fakufaku** [comment]
In the paper, the rows of `W` are defined as `w^H`, so the algorithm is just consistent with this definition.
To see it, you can breakdown line 162 in two steps
```python
w = np.linalg.solve(WV, eyes[:, :, s])
W[:, s, :] = np.conj(w)
```

If you want to store the non-conjugated demixing filters in `W`, then you will need to add a conjugate operation around `W` in all other equation, e.g., (25).

**Comment by MordehayM** [comment]
OK, got it.
two more questions please:
1. About the scale restoration of the signal. The paper cited this paper "An Approach to Blind Source Separation Based on Temporal Structure of Speech Signals" but I don't see in the paper the projection_back function implemented here( https://github.com/LCAV/pyroomacoustics/blob/fa064c2b9db39f1245ef22501c63dd4575c8656a/pyroomacoustics/bss/common.py#L29). Can you direct to the paper of this implementation?
2. About the normalization to prevent ambiguity(https://github.com/LCAV/pyroomacoustics/blob/fa064c2b9db39f1245ef22501c63dd4575c8656a/pyroomacoustics/bss/ilrma.py#L176). I've encountered another set of normalization equations in the paper titled "Determined Blind Source Separation Unifying Independent Vector Analysis and Nonnegative Matrix Factorization." While I suspect they are identical, my query is regarding their origin—specifically, which paper served as their source?
Thanks

**Comment by fakufaku** [comment]
1. You are totally right, I made a mistake in the original paper. The method used is "minimal distortion principle" from the paper: K. Matsuoka and S. Nakashima, “Minimal distortion principle for blind source separation,” in Proc. ICA, San Diego, Dec. 2001, pp. 722–727. For a short introduction to the two methods, you can refer the background section of [my paper on the topic](https://www.isca-archive.org/interspeech_2020/scheibler20_interspeech.html).
2. Are you referring to equations (43)-(46) in the paper? I think they are the same. In the implementation, in addition to `w` and `R`, we keep track of `P`, the power of `y` and `T`, one of the factors of `R`.  Both these factors are squared values and must be normalized by the square of lambda.

**Comment by fakufaku** [comment]
Closing this if there is no further discussion.
