### ISSUE TITLE
Error in pyroomacoustics/pyroomacoustics /beamforming.py

### ISSUE THREAD

**Issue by AVer-V003000** [LCAV/pyroomacoustics#348]
Hi,

I noticed that there might be an error in beamforming.py

at line 301:
  **R = circular_2D_array(center=center[:1], M=M, phi0=phi0, radius=radius)**

I think **center=center[:1]** should be modified as **center=center[:2]**, for a 2D array

Correct me if I'm wrong, thanks :))

**Comment by fakufaku** [comment]
Thanks for finding this bug ❤️ I corrected it in PR #350.
