### ISSUE TITLE
Plot of Microphones

### ISSUE THREAD

**Issue by jordanalwon** [LCAV/pyroomacoustics#355]
When I add multiple microphones or multiple microphone arrays, only one of them is displayed.
In line 1562 and 1775 of room.py, the iterator for the microphones should be self.mic_array.M and not self.mic_array.nmic.

**Comment by fakufaku** [comment]
Thanks for reporting this. I will look into it.

**Comment by fakufaku** [comment]
Finally looking at this. I noticed several holes in the MicrophoneArray class potentially leading to such bugs. I tried to plug them with PR #387 .
Please try again after the PR is merged and let me know if this fixes your problems.
