### ISSUE TITLE
Potential bug when generating RT60 using v0.7.5

### ISSUE THREAD

**Issue by michaeljconnolly** [LCAV/pyroomacoustics#358]
Hi,

Running the pyroomacoustics_demo notebook, I've noticed that the RT60 generated using version 0.7.5 is significantly different than the RT60 generated using versions 0.7.3 and 0.7.4.

I tested further with my own scripts, that are similar to the demo notebook (both attached here: [scripts.zip](https://github.com/user-attachments/files/16267620/scripts.zip)). One uses ray tracing (raytracing.py), and the other uses ISM (ism.py).

For raytracing, the RT60 is ~40 ms for v0.7.5, but ~280 ms for both v0.7.3 and v0.7.4. 

For ISM, the RT60 is 7 ms for v0.7.5, but 31 ms for both v0.7.3 and v0.7.4.

I have reproduced these results using docker containers, built with the provided Dockerfile (changing pyroomacoustics version only).

I wonder if this is a bug, or if I'm missing something?

Thanks for your help.

**Comment by fakufaku** [comment]
@michaeljconnolly thanks for the heads up!
Actually, I have updated the code for the RT60 to be more robust.
The new code will ignore outlier samples at the tail of the energy curve to try to get a better fit.
Have you tried to check which results makes more sense wrt to the actual RIR?
If you provide `plot=True` as an argument to `measure_rt60`, it should also show a plot that should make it clear if there is a problem or not.

**Comment by michaeljconnolly** [comment]
You're welcome, and thanks for your response!

I have plotted the RIR for one microphone and the RT60 for 0.7.3, 0.7.4 and 0.7.5. These examples closely follow the demo notebook (ray tracing with 1000 rays, max_order 3).

It looks like, the RIR tails off at ~150ms. It is interesting that for the 0.7.5 RT60 plot, the energy does not fall to -60dB.

Images below:

0.7.3
![0 7 3](https://github.com/user-attachments/assets/ee8ebf94-d9ac-450f-a86b-873e4b1223a1)

0.7.4
![0 7 4](https://github.com/user-attachments/assets/9993d270-bf2a-469f-a3e9-6572d8b9fd40)

0.7.5
![0 7 5](https://github.com/user-attachments/assets/537a4e7c-687d-481b-94d3-6241b3000440)

Thanks again for your feedback.

**Comment by fakufaku** [comment]
Thanks! It looks like the default value of the `energy_thresh` parameter is too low. Could you please try to set it to 0.99 or 0.999?

**Comment by michaeljconnolly** [comment]
No problem. I have added some plots for v0.7.5, setting energy_thresh to 0.99, 0.999 and 1.0. The RT60 lines up with 0.7.3 and 0.7.4, when set to 1.0. With energy_thresh set to 0.99 and 0.999, the energy does not fall to -60dB.

Images below:


energy_thresh 0.99
![thres_0 99](https://github.com/user-attachments/assets/67030907-425c-4b1d-90bd-6bff47ef4ac6)

energy_thresh 0.999
![thres_0 999](https://github.com/user-attachments/assets/ef68825c-0a62-41cf-af1e-8c0087aa4cd7)

energy_thresh 1.0
![thres_1 0](https://github.com/user-attachments/assets/753a05b1-0d1e-40d2-8645-25190f4cd547)

**Comment by fakufaku** [comment]
It looks like the `energy_thres` parameter is more difficult to use than I anticipated.
For now I will change the default to `1.0` to match the previous behavior of the function.

**Comment by michaeljconnolly** [comment]
Perfect, thanks for your help with this!
