### ISSUE TITLE
Question on Material Database

### ISSUE THREAD

**Issue by Kanafani80** [LCAV/pyroomacoustics#369]
Hi! Thanks again for this great repo.

I have a question on the material database:
https://pyroomacoustics.readthedocs.io/en/stable/pyroomacoustics.materials.database.html

I am wondering if there is a reference for these numbers? I could not see one listed. Where do they come from? I am interested in both validating them and seeing if there are more materials or info in the reference. 

Thank you!

**Comment by fakufaku** [comment]
Sorry for the late reply. The table was taken from the appendix of the following [book](https://link.springer.com/book/10.1007/978-3-540-48830-9).
```
Michael Vorlaender, Auralization: Fundamentals of Acoustics, Modelling,
Simulation, Algorithms, and Acoustic Virtual Reality, Springer, 1st Edition,
2008.
```

**Comment by Kanafani80** [comment]
Thanks!!
