### ISSUE TITLE
Cannot import pyroomacoustics

### ISSUE THREAD

**Issue by WeiXipin** [LCAV/pyroomacoustics#372]
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-ac8b5d4f9041>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import pyroomacoustics as pra

1 frames
[/usr/local/lib/python3.10/dist-packages/pyroomacoustics/__init__.py](https://localhost:8080/#) in <module>
    125 from . import phase, transform
    126 from .acoustics import *
--> 127 from .beamforming import *
    128 from .directivities import *
    129 from .metrics import *

[/usr/local/lib/python3.10/dist-packages/pyroomacoustics/beamforming.py](https://localhost:8080/#) in <module>
     31 from . import utilities as u
     32 from . import windows
---> 33 from .directivities import DirectionVector, Directivity, Omnidirectional
     34 from .parameters import constants
     35 from .soundsource import build_rir_matrix

ModuleNotFoundError: No module named 'pyroomacoustics.directivities'

**Comment by fakufaku** [comment]
Centralizing the issue in #371
