### ISSUE TITLE
Room.add_microphone_array() loses array directivity when using MicrophoneArray class

### ISSUE THREAD

**Issue by mmjamm** [LCAV/pyroomacoustics#382]
Lovely library! Here's a small bug I stumbled upon.

Room.add_microphone() method accepts arraylike or instance of MicrophoneArray for the first parameter.
When using MicrophoneArray with a defined directivity, the directivity is lost.

Steps to reproduce:
```
from pyroomacoustics import AnechoicRoom
from pyroomacoustics.beamforming import MicrophoneArray
from pyroomacoustics.directivities import FigureEight, DirectionVector
import numpy as np

fs = 16000
room = AnechoicRoom(fs=fs)

mic_locs = np.c_[
    [6.3, 4.87, 1.2]
]

dir_obj = FigureEight(
    orientation=DirectionVector(azimuth=90, colatitude=15, degrees=True)
)

mic_array = MicrophoneArray(mic_locs, fs, [dir_obj])

room.add_microphone_array(mic_array)
print(f"Directivity, case 1: {room.mic_array.directivity}")

room.add_microphone_array(mic_locs, [dir_obj])
print(f"Directivity, case 2: {room.mic_array.directivity}")
```

Output of the above code:
```
Directivity, case 1: [None]
Directivity, case 2: [None, <pyroomacoustics.directivities.analytic.FigureEight object at 0x7fd48955b700>]
```

I think the bug is in (room.py) add_microphone_array where it assumes that a directivity function parameter is always supplied. IMO it would make more sense to use the directivity already contained in the MicrophoneArray object:
```
if not isinstance(mic_array, MicrophoneArray):
   # if the type is not a microphone array, try to parse a numpy array
   mic_array = MicrophoneArray(mic_array, self.fs, directivity)
else:
   # if the type is microphone array
   mic_array.set_directivity(directivity)
```

Version used to reproduce:  `0.8.2`

**Comment by fakufaku** [comment]
Thanks for catching this. You are totally right and this is a bug.

**Comment by fakufaku** [comment]
So after checking, I recalled that the current API was designed so that you can provide the microphone array information as either
1. A MicrophoneArray object, that should contain microphone locations and directivities.
2. A pair of numpy array containing the locations, and a list of corresponding directivities (the `directivity` parameter of the method).

I will add a check that makes the method fail when `mic_array` is a MicrophoneArray object and directivity is not `None`.

**Comment by fakufaku** [comment]
Thanks for your patience. This should be now fixed in master.
I'm trying to fix a couple of other issue before updating pypi.

**Comment by mmjamm** [comment]
The change looks good. Thanks for handling this issue and for the great library!
