### ISSUE TITLE
Zero-padding

### ISSUE THREAD

**Issue by maelp** [LCAV/pyroomacoustics#41]
Are you actually using zero-padding when computing the beamformer result? I saw that the default are set to 0, won't this lead to aliasing when using circular convolutions corresponding to the filter frequency-domain multiplication?

**Comment by fakufaku** [comment]
Hi @maelp , indeed, you will need to set the proper amount of zero-padding when doing frequency domain filtering. It might indeed be a good idea to set reasonable default values there. Also, we have updated the STFT implementation (the new one is in `realtime` sub-package) and should probably fix the beamforming class to use this one.

Another thing you need to be careful is that your filter also needs to be zero padded when doing FD convolution. This might not be completely obvious when the beamforming weights are computed directly in the frequency domain.

**Comment by maelp** [comment]
Hi @fakufaku thanks for this answer! So if I understand correctly, the "correct way" to do FD filtering would be this:

 - do a regular STFT of size N without zero-padding to get analysis data
 - compute the beamforming weights (for instance for MVDR, GEV) from this, which will give weights which are of length N, and corresponding to a time-domain convolution of length N
 - then do a second STFT of size 2N with N elements zero-padded (or 2N elements and use overlap-save) and filter with the N weights zero-padded to 2N

this seems a bit computation-hungry though, and I never saw this done in any codebase I saw, so this is why I was wondering if this was the "correct way" to do it, or if there are reasons why someone can do the beamforming without zero-padding?

I was assuming that the justification would be that if we do hops of size L << N and we recover only the L central coefficients, and that the data has been windowed, then the influence of the circular convolution on those L elements would be small, and we wouldn't need to do the 2N zero-padding?

**Comment by fakufaku** [comment]
@maelp There is a way to save the first STFT computation.

* Do an STFT of size 2N with zero-padding
* Compute the filter weights on the even frequencies only (So only N coefficients)
* Do interpolation of the filter weights using FFT to get 2N weights

The interpolation is done by

1. setting all the odd weights to zero
2. perform iFFT of size 2N
3. setting to zero the second half of the filter
4. doing FFT to go back to frequency domain where the odd frequencies will have been interpolated

The only extra step needed compared to a "conventional" setup is the last point which only costs 2 FFT (very small compared to cost of STFT).

This is indeed if you want to do perfect, efficient overlap-add filtering. Now, as you mention above this is rarely done with most implementation using half overlap with a Hann or Hamming window. If the filters are not too wild, the artefacts from the circular convolution will not be perceptible.

**Comment by maelp** [comment]
Thanks!

**Comment by fakufaku** [comment]
@maelp Ah, forgot the detail that when omitting zero-padding and relying on overlapping frames and windowing, it is important to use a *synthesis* window matching the analysis one. We recently added a [function](https://pyroomacoustics.readthedocs.io/en/latest/pyroomacoustics.realtime.stft.html?highlight=synthesis#pyroomacoustics.realtime.stft.compute_synthesis_window) to compute the optimal synthesis window given the analysis one.

**Comment by maelp** [comment]
I guess this is the Griffin-Lim normalization?

**Comment by maelp** [comment]
Isn't this more linked to the fact that we are modifying the spectrum, so we want to get the best L2 approximation of a signal matching the modified spectrum (so we don't get a complex signal when inverting?)

**Comment by fakufaku** [comment]
This is indeed the Griffin-Lim criterion. It is almost as you say: you are trying to find the time-domain signal whose STFT will be closest to your (modified) STFT measurements. This is most useful when the modifications are non-linear (like artefacts from the circular convolution). If the transformation is linear (like filtering is), then it is still possible to get perfect reconstruction without the need of a synthesis window.
(Note that the inverted signal will never be complex if you impose conjugate symmetry of the spectrum)
