### ISSUE TITLE
Different sampling rates for audio sources

### ISSUE THREAD

**Issue by manuelhuber** [LCAV/pyroomacoustics#44]
Currently the sampling rate is defined by the room - what is the recommended way of dealing with different sampling rates in my audio sources? Resample them beforehand?

**Comment by fakufaku** [comment]
I'm sorry it took so long to answer your question! Yes, the recommended way is resampling beforehand. I find the `samplerate` package to be fast and intuitive.

**Comment by fakufaku** [comment]
I'll close this one for now. Do not hesitate to reopen if you have more questions. Cheers
