### ISSUE TITLE
Export impulse response coefficients to use with SoX

### ISSUE THREAD

**Issue by EgorLakomkin** [LCAV/pyroomacoustics#49]
Hi!

Is it possible to export FIR filter coefficients of the generated room so it would be possible to use it with SoX, for example, afterward?

**Comment by fakufaku** [comment]
Hi, I don't really what format SoX expects, but you can access all the impulse responses in `room.rir`, which is a list of lists with the outer list going over microphones and the inner list over sources. There are standard numpy arrays, so provided you can export the numpy array to a format SoX expects, it should work.

**Comment by EgorLakomkin** [comment]
Thank you!
