### ISSUE TITLE
Absorption of Sound in Air versus Humidity and Temperature 

### ISSUE THREAD

**Issue by Sylvus** [LCAV/pyroomacoustics#58]
First of all, this is an awesome project, thank you for putting in the time and effort!

I was wondering how you deal with the absorption of sound. Do you consider this aspect at all or ignore it completely? If you do consider it, would it be possible to have parameters for humidity and temperature? This paper, for example, describes the various ways different frequencies are absorbed: http://gradbena.fizika.si/HarrisJASA66.pdf

Also, if I generate an impulse response (IR) then that should contain all the necessary information about reverb and distance, correct? So if I convolve an arbitrary sound signal with the recorded IR that should give me a realistic approximation not only including the reverb effect but also the absorption effect. 

Again, thank you very much for this project,
Sylvus

**Comment by fakufaku** [comment]
Meanwhile, air absorption has been implemented! 🎉 Please have a look at the documentation.
