### ISSUE TITLE
Trying to find the distance between the source and the microphones

### ISSUE THREAD

**Issue by akhilvasvani** [LCAV/pyroomacoustics#61]
Hi, 

I am trying to find the distance between the center of my microphone array and the source sound in a 3-D environment.  I have looked through the source code, and I see it can support it. However, I am unsure of two things. The first is if the DOA methods—SRP, MUSIC, TOPS, FRIDA—themselves can support source localization in 3-d. And secondly, regardless if they can or cannot, I am trying to use the algorithms so find me the distance between the source and the center of my microphone array. Is this possible to do?

NOTE: I have put in comments safety check for a comparison sake. I would like to remove this once I figure out the problems listed above.

See my code below:

    import numpy as np
    import matplotlib.pyplot as plt
    from scipy.io import wavfile
    from scipy.signal import fftconvolve
    import IPython
    import pyroomacoustics as pra

    #Build 3-D Representation of the room
    room = pra.ShoeBox([13.75,8.66,9.5], fs=16000, absorption=0.35, max_order=17)

    #Add Source
     fs,signal
    =wavfile.read("/Users/akhilvasvani/Downloads/cmu_us_awb_arctic/wav/arctic_b0528.wav")

    room.add_source([(13.75/2),(8.66/2),(9.5/2)], signal=signal)

    #Add 12-microphone array
    R = np.c_[       # [x, y, z]
        [2.85, 0, 0.49], # mic 4
        [4.82, 0, 0.49], # mic 8
        [5.80, 0, 0.49], # mic 12
        [2.85, 0, 2.65], # mic 3
        [4.82, 0, 2.65], # mic 7
        [5.80, 0, 2.65], # mic 11
        [2.85, 0, 4.81], # mic 2
        [4.82, 0, 4.81], # mic 6
        [5.80, 0, 4.81], # mic 10
        [2.85, 0, 6.97], # mic 1
        [4.82, 0, 6.97], # mic 5
        [5.80, 0, 6.97]  # mic 9
        ]

    room.add_microphone_array(pra.MicrophoneArray(R, room.fs))

    fig, ax = room.plot()
    ax.set_xlim([0, 14])
    ax.set_ylim([0, 9]);
    ax.set_zlim([0, 10]); # for 3-d

    room.simulate()

    from pyroomacoustics.doa import great_circ_dist

    #Safety-Check
    center = [4.325, 0, 3.730]
    source = [(13.75/2),(8.66/2), (9.5/2)] # I have specified the source location. 
    temp = np.arctan([0,(source[2]-center[2])/(source[0]-center[0])]) #for some dumb reason, we need to have an array with[0, (desired value)]
    radius = np.sqrt(((source[2]-center[2])**2)+((source[0]-center[0])**2)) #

    azimuth = temp[1] # in radians
    c = 343.    # speed of sound
    fs = 16000  # sampling frequency
    nfft = 256  # FFT size
    freq_range = [2900, 3500]

    X = np.array([pra.stft(signal, nfft, nfft // 2, transform=np.fft.rfft).T for signal in room.mic_array.signals])

    # Now we can test all the algorithms available
    algo_names = ['SRP', 'MUSIC', 'FRIDA', 'TOPS'] 
    spatial_resp = dict()

    for algo_name in algo_names:
        # Construct the new DOA object
        # the max_four parameter is necessary for FRIDA only
        doa = pra.doa.algorithms[algo_name](L=R, fs=fs, nfft=nfft, c=c, num_src=1, max_four=4)
    
        doa.sph_plot_diracs()
        plt.title(algo_name)
    
        # doa.azimuth_recon contains the reconstructed location of the source
        print(algo_name)
        print('  Recovered azimuth:', doa.azimuth_recon / np.pi * 180., 'degrees')
        print('  Error:', great_circ_dist(azimuth, doa.azimuth_recon) / np.pi * 180., 'degrees')

        plt.show()
        print((doa.azimuth_recon))

**Comment by jay-pee** [comment]
As far I know, you can't calculate distance with these algorithms. There are efforts made to calculate the distance from the coherent-to-defuse ratio but this is not very reliable, because it is strongly depended on the room measures. However, this would be of course very helpful for a lot of applications. From this algorithms you only get azimuth and elevation angle.

**Comment by fakufaku** [comment]
That is correct, most of these algorithms only return the angles. With the exception of SRP-PHAT which seems to have a `near` field mode (see the [doc](https://pyroomacoustics.readthedocs.io/en/pypi-release/pyroomacoustics.doa.srp.html#module-pyroomacoustics.doa.srp) ans [source](https://github.com/LCAV/pyroomacoustics/blob/master/pyroomacoustics/doa/srp.py)). In this case, you also provide a list of candidate distances `r` which is used to produce mode vectors with different norms. I don't know if the near field SRP has been really tested, so please let us now the result.

**Comment by akhilvasvani** [comment]
I have tried testing it with several radius values. Not much difference. Anyhow, solved a couple of my problems. Thank you.

**Comment by fakufaku** [comment]
@akhilvasvani One last thing, I saw that your microphones are separated by several meters. In that case, the frequency range `[2900, 3500]` will be plagued by aliasing. You need to use much lower frequency, say `[100, 500]`.

**Comment by akhilvasvani** [comment]
How do you know which Frequency bands to use based on the microphone spacing? Is there a set formula?

**Comment by fakufaku** [comment]
@akhilvasvani 

* The speed of sound is precisely 343 m/s in the simulation and should not be influenced by the room size.
* The DOA accuracy will be affected by the reverberation time of the room. Try setting the reverberation time to zero to see if the detection is correct in that case.
* You are right about the formula I use. I would select frequencies that are not too far from `d / 343`, where `d` is the inter-microphone spacing.

**Comment by akhilvasvani** [comment]
Thanks.

**Comment by ELELUABDULSALAM** [comment]
Hey @akhilvasvani. I am currently trying to find the distance between the sound source and microphone array, the DOA algorithm just provides us with the angle of the sound source. Are you able to use the lib to figure out the distance?

**Comment by fakufaku** [comment]
@ELELUABDULSALAM , the DOA algorithms in the package are not appropriate to find the distance.

**Comment by ELELUABDULSALAM** [comment]
@fakufaku what do you suggest I use to locate the sound distance

**Comment by fakufaku** [comment]
I have replied in issue #243 .

**Comment by akhilvasvani** [comment]
@ELELUABDULSALAM, as @fakufaku and you mentioned, the pyroomacoutics library provides angles where the sound source is located. That said, I am exploring an alternative strategy of using a clustering to determine the true sound source location given multiple candidate locations. Check out my [repo](https://github.com/akhilvasvani/Sound-Source-Localization).

**Comment by akhilvasvani** [comment]
> I have replied in issue #243 as well with a question.
