### ISSUE TITLE
Phase inversion upon sound reflection

### ISSUE THREAD

**Issue by qwertzuii** [LCAV/pyroomacoustics#63]
Hi,
Does this implementation consider the phase inversion of sound upon each reflection at the room boundaries? If not, would it be difficult to implement this?

**Comment by fakufaku** [comment]
Hi @qwertzuii , the phase is not necessarily inverted at each reflection. In general, there is a partial phase rotation. Regardless, the simulator does not currently have the capability to take this into account. One way to see this is that we are using a 'hard' wall approximation.

**Comment by fakufaku** [comment]
Closed due to lack of activity.
