### ISSUE TITLE
python typo pyroomacoustics.soundsource.add_signal

### ISSUE THREAD

**Issue by Owen864720655** [LCAV/pyroomacoustics#65]
This method should provide `self` as the first argument. The proper form is as follows:
```python
def add_signal(self, signal):
    self.signal = signal
```
Please revise it.

**Comment by fakufaku** [comment]
Thanks for raising this up. A patch is coming.

**Comment by fakufaku** [comment]
Fixed in master. A new release will follow soon. Thanks again!
