### ISSUE TITLE
DOA Azimuth and Colatitude angles in reference to 

### ISSUE THREAD

**Issue by akhilvasvani** [LCAV/pyroomacoustics#68]
When I perform any of the DOA algorithms, I get a azimuth and colatitude reconstructed angle. Where exactly is my baseline for these angles to compare? Is it from the center of my microphone array? 

Let's give an example. 

Say I have two microphones 0.05 meters apart. I run the simulation and I perform DOA and I get an azimuth angle of -78 degrees and colatitude of 89 degrees. Where is the -78 degrees angle and colatitude of 89 degrees in reference to? Is it the center of the two microphones?

**Comment by fakufaku** [comment]
Sorry I haven't answered this yet. I'll come back to you about it shortly!

**Comment by akhilvasvani** [comment]
I think it's through the center of both microphones. But what have you say if there are 3 or 4 microphones?

**Comment by fakufaku** [comment]
This is correct. When there are more than 2 microphones, the origin is the geometric center of all the microphones (the average of their coordinates).

The azimuth angle is in the x-y plane, with the x-axis towards zero and rotating counter-clockwise. The elevation goes from -pi / 2 towards the negative z-axis to pi / 2 towards the positive z axis.
