### ISSUE TITLE
Amplitude normalization

### ISSUE THREAD

**Issue by Owen864720655** [LCAV/pyroomacoustics#70]
After define a `room` and feed the input signal, we get the output via:
```
room.simulate(recompute_rir=True)
output = room.mic_array.signals
```
Need we normalize the output to get the proper amplitude, and how to get there?

Thanks

**Comment by fakufaku** [comment]
This depends on what you want to do. If you are only using a single microphone, then the amplitude is not so important and you can rescale it as you see fit. When using multiple microphones, the simulator will compute the correct relative amplitudes of all the microphones. Here again, an arbitrary scaling factor can be applied, as long as it is applied to the signals from all microphones.
