### ISSUE TITLE
Generating wav

### ISSUE THREAD

**Issue by maelp** [LCAV/pyroomacoustics#8]
Hi, I'm interested by creating a geometry and generating wav at the microphone location with different sources, as I'm new to room acoustics I'd like to know if you could give me a hint:

 - is there an example where I can create a room with a microphone and multiple sources, and "play" wave through the sources and record at the microphone, or do we have to get a RIR for each source and create the resulting .wav ourselves by convolving?
 - should we use 2d or 3d rooms when we want to do simple room acoustics and audio creation to simulate a real room condition?
 - how does the methods from this module compare to this kind of code http://www.eric-lehmann.com/ism_bg.html

thank you

**Comment by fakufaku** [comment]
Hi @maelp , I'll answer in order.
1) That's a perfectly valid thing to want! I think it should be possible to do this without too much effort. I will try to write an example in the next few days.
2) Wether one wants to use 2D or 3D is entirely dependent on the situation I guess. The situation in research in acoustical signal processing is that many people validate their algorithms in 2D room environments. Now I think this has more to do with ease of implementation than accuracy. You can imagine that a 2D room is like a room without floor or ceiling (an infinite elevator shaft). If you are interested in realistic rendering, I would use a 3D room. Then again, the image source model is not the most life-like simulator to use. 
3) I have not used the simulator from Eric Lehmann, but if I recall correctly, it uses a more sophisticated method to improve the rendering of the tail of the RIR, but has the drawback of only handling shoebox rooms and requires Matlab.

**Comment by fakufaku** [comment]
Closed by mistake. I'll close the issue when the example is added :)

**Comment by maelp** [comment]
Thanks Robin


On 8 October 2017 at 09:13:29, Robin Scheibler (notifications@github.com)
wrote:

Reopened #8 <https://github.com/LCAV/pyroomacoustics/issues/8>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LCAV/pyroomacoustics/issues/8#event-1283098175>, or mute
the thread

**Comment by fakufaku** [comment]
Finally, I could do this quickly. I have added `room_simulation.py` in the [examples](https://github.com/LCAV/pyroomacoustics/blob/master/examples/room_simulation.py) folder. I hope this helps.

```
'''
A simple example of using pyroomacoustics to simulate
sound propagation in a shoebox room and record the result
to a wav file.
'''

import numpy as np
import pyroomacoustics as pra
import matplotlib.pyplot as plt
from scipy.io import wavfile

fs, audio_anechoic = wavfile.read('examples/samples/guitar_16k.wav')

# room dimension
room_dim = [5, 4, 6]

# Create the shoebox
shoebox = pra.ShoeBox(
    room_dim,
    absorption=0.2,
    fs=fs,
    max_order=15,
    )

# source and mic locations
shoebox.add_source([2, 3.1, 2], signal=audio_anechoic)
shoebox.add_microphone_array(
        pra.MicrophoneArray(
            np.array([[2, 1.5, 2]]).T, 
            shoebox.fs)
        )

# run ism
shoebox.simulate()

audio_reverb = shoebox.mic_array.to_wav('examples/samples/guitar_16k_reverb.wav', norm=True, bitdepth=np.int16)
```

**Comment by maelp** [comment]
Thanks @fakufaku, would this be correct to simulate the reverb:

 - create the room
 - create a source which emits a single sample with amplitude 1.0
 - get the `audio_reverb`
 - convolve wav with it

**Comment by fakufaku** [comment]
Dear @maelp , as I understand, you are interested to look at the room impulse response of the room. There is a simpler way to do this. When you run the `shoebox.simulate()` line above, all room impulse responses will be computed and stored in `shoebox.rirs`. Then, the impulse response between the `m`-th microphone and the `s`-th source can be accessed at `shoebox.rirs[m][s]`.

In case you are only interested in getting the impulse response (as opposed to simulate the propagation of a particular sound sample), you can omit the source signal specification and call `shoebox.compute_rir()` instead of `simulate()`. Here is the modified example.
```
'''
A simple example of using pyroomacoustics to compute
the room impulse response between one source and one microphone.
'''

import numpy as np
import pyroomacoustics as pra
import matplotlib.pyplot as plt

# room dimension
room_dim = [5, 4, 6]

# Create the shoebox
shoebox = pra.ShoeBox(
    room_dim,
    absorption=0.2,
    fs=fs,
    max_order=15,
    )

# source and mic locations
shoebox.add_source([2, 3.1, 2])
shoebox.add_microphone_array(
        pra.MicrophoneArray(
            np.array([[2, 1.5, 2]]).T, 
            shoebox.fs)
        )

# run ism
shoebox.compute_rir()

# this plots the RIR between the 1st source and the 1st microphone
rir_time = np.arange(len(shoebox.rir[0][0])) / shoebox.fs
plt.plot(rir_time, shoebox.rir[0][0])
```

**Comment by maelp** [comment]
Thanks !
