### ISSUE TITLE
How to use plot_beamformer_from_point

### ISSUE THREAD

**Issue by xaviliz** [LCAV/pyroomacoustics#84]
Hi all,

I was checking Beamformer class, can you explain how plot_beamformer_from_point function works or provide a simple example. Thanks in advance!

**Comment by fakufaku** [comment]
Hi @xaviliz , I assume you are refering to `pyroomacoustics.beamforming.Beamformer.plot_response_from_point`.

The function signature is
```
plot_response_from_point(self, x, legend=None)
```
where `x` is a `(dim, n_points)`-shaped array of vectors. The function will compute the frequency response of the beamformer at each of these points and plot them. The keyword argument `legend` lets you give a custom legend to the curves (all `n_points` of them).

**Comment by xaviliz** [comment]
Thanks, I got it!

I have tried a simple test with three sources. I have realized it is no necessary to add_sources() to Room class (`pyroomacoustics.beamforming.Room.add_sources()`). Is that correct? I thought sources had to be added.

**Comment by fakufaku** [comment]
No, you don't need to. This function was written to create beampattern plots for beamformers. In fact, you don't even need a `Room` for that one either. It only needs to have some beamforming weights.

**Comment by xaviliz** [comment]
Ok @fakufaku , thanks for your clarification. I will try to compute weights for an specific angle, I have tried pyroomacoustics.beamforming.Beamformer.far_field_weights() but I am not sure if this is the best way for close field cases.
