### ISSUE TITLE
Error in running test_doa.py

### ISSUE THREAD

**Issue by jimtal001** [LCAV/pyroomacoustics#87]
Hello, I hope you can assist me.

I am running test_doa.py and noticed that the number of points M is set to 12 rather than 6 (as stated in the comment line).  When I replace the 12 with 6 an error is issued from utilities.py, line:
bank_flat[indices.ravel()] = windows * np.sinc(sinc_times.ravel())

# circular microphone array, 6 mics, radius 15 cm
R = pra.circular_2D_array([0, 0], 12, 0., 0.15)

Thank you!

**Comment by fakufaku** [comment]
Thanks for reporting this. I am looking into the issue.

**Comment by fakufaku** [comment]
@jimtal001 I could fix the bug in master, thank you for your help!

**Comment by jimtal001** [comment]
I am excited to learn more about this tool as I begin to work with it.  
Qestions:  
Is there any documentation on how to use the functionality of pyroomacoustics?
Is there a sample that shows how to integrate real microphone with pyroomacoustics?
Is there a doa example that can resolve both azimuth and elevation?

Thanks again!
Jim
