### ISSUE TITLE
how to set cardiac recv w/ multiple direction? 

### ISSUE THREAD

**Issue by yhgon** [LCAV/pyroomacoustics#95]
I have one question for microphone setting.  multiple  direction cardiac recv.  for exmaple, 5 direction of "0, 45, 90, 135, 180 degree " on same position. 

When I put 8 mic  circular array
`center=[20,20,1], mic=8,  align=0, radius=0.1`
Position was well but no cardiac microphone direction. 

Any tip to implement the option to adjust amp for each config?

**Comment by yhgon** [comment]
it's same issue of https://github.com/LCAV/pyroomacoustics/issues/85

**Comment by fakufaku** [comment]
@yhgon Right! Sorry for the late reply. Currently this is not implemented in pyroomacoustics, but it wouldn't be too hard to add I think.

If you have an analytic response for your microphone, all you need to know is the angle between the microphone and the image sources. The location of the image sources is in `SoundSource.images` and the corresponding attenuations are in `SoundSource.damping`.

The room impulse response is computed in `SoundSource.get_rir` [here](https://github.com/LCAV/pyroomacoustics/blob/master/pyroomacoustics/soundsource.py#L202). What you would need to do is to multiply `alpha[k]` on line 216 with the directional attenuation of the microphone at the angle between `mic` and `self.images[k]`.

This is really something that I'd like to add in the future, but haven't gotten around to yet.
